import { notFound } from 'next/navigation'
import { ChevronRight } from 'lucide-react'
import { Cta, FAQList, Hero, StatusBadge } from '@/components/public-site'
import { ResponsibilityNotice } from '@/components/role-entry'

const content: Record<string, {
  title: string
  eyebrow: string
  intro: string
  imageAlt: string
  benefits: string[]
  responsibilities: string[]
  notThis: string
  status: string
  cta: string
  href: string
  faq: [string, string][]
}> = {
  rider: { title: 'Rider', eyebrow: 'Safety network member', intro: 'A rider joins to understand safer preparation, discover community pathways and contribute real road context without being promised live coverage.', imageAlt: 'Conceptual scene of riders reviewing a route map together; not a verified BBBT group or event.', benefits: ['Explore rider safety guidance and readiness concepts', 'Discover groups, rides and shared community pathways', 'Build a clearer personal profile and safety context', 'Contribute feedback that can shape future systems'], responsibilities: ['Ride responsibly and follow applicable law', 'Keep personal details accurate and protect other riders’ privacy', 'Treat prototype tools as coordination aids, not emergency dispatch', 'Share feedback honestly and respectfully'], notThis: 'Not a live emergency service, medical network, guaranteed response system or nationwide coverage promise.', status: 'PROTOTYPE PATHWAY', cta: 'Join as a Rider', href: '/signup?role=Rider', faq: [['What do I get as a Rider?', 'You get a clearer entry into BBBT’s safety and community prototype, including public guidance and controlled member pathways. Specific live benefits will only be introduced when verified.'], ['Do I need to pay?', 'No payment is collected through this prototype. Membership pricing and token economics are intentionally not presented as settled facts.']] },
  'group-admin': { title: 'Group Admin', eyebrow: 'Community coordinator', intro: 'A Group Admin brings an existing riding community into a more accountable pathway for discovery, participation and safety communication.', imageAlt: 'Conceptual group ride planning scene; not a verified BBBT group.', benefits: ['Create a clearer public-facing group pathway', 'Coordinate group information and member participation', 'Connect group context to future ride and safety tooling', 'Help identify practical needs without overstating coverage'], responsibilities: ['Maintain accurate group information and obtain informed consent', 'Do not collect unnecessary personal data', 'Set clear expectations for members and moderators', 'Escalate emergencies to appropriate services rather than BBBT prototype tools'], notThis: 'Not authority over BBBT Trust, not emergency command, and not permission to publish private member information.', status: 'SHARED PROTOTYPE', cta: 'Join as Group Admin', href: '/signup?role=Group%20Admin', faq: [['What does a Group Admin receive?', 'The current pathway is for controlled exploration of group identity, public discovery and future shared tools. It does not guarantee verified members, dispatch or nationwide support.'], ['Can I add my group now?', 'You can start the role application. Group data and any public listing remain subject to controlled review and the current prototype state.']] },
  'group-marshal': { title: 'Group Marshal', eyebrow: 'Group safety contributor', intro: 'A Group Marshal supports safer participation inside a defined community while staying within clear limits of responsibility.', imageAlt: 'Conceptual rider safety briefing with helmets and a route map; not a live BBBT operation.', benefits: ['Learn the intended Trust Protocol and readiness approach', 'Support calmer group communication and preparation', 'Contribute incident-learning feedback', 'Help make safety expectations visible before rides'], responsibilities: ['Follow the group’s agreed safety practice and local law', 'Avoid presenting yourself as medical, police or emergency authority', 'Protect rider dignity, consent and privacy', 'Keep observations factual and escalate appropriately'], notThis: 'Not a substitute for police, ambulance, medical care, trained emergency response or guaranteed BBBT intervention.', status: 'ROLE BRIEF', cta: 'Join as Group Marshal', href: '/signup?role=Group%20Marshal', faq: [['What is the difference from a Group Admin?', 'A Group Admin coordinates the community pathway. A Group Marshal is a safety contribution role focused on preparation and responsible group participation.'], ['Is marshal training live?', 'Training and assessment concepts exist in the product direction, but this public prototype does not certify emergency or medical capability.']] },
  'independent-marshal': { title: 'Independent Marshal', eyebrow: 'Cross-community safety contributor', intro: 'An Independent Marshal is an experienced rider exploring a future contribution role beyond one group or local community.', imageAlt: 'Conceptual experienced rider preparing route and safety equipment; not a verified marshal network.', benefits: ['Explore a future cross-community contribution pathway', 'Bring road intelligence from different riding contexts', 'Help test standards without claiming operational authority', 'Support a culture of preparation and respectful coordination'], responsibilities: ['Act within confirmed scope and never imply guaranteed response', 'Respect group ownership and local context', 'Protect personal and incident information', 'Wait for defined verification before representing BBBT publicly'], notThis: 'Not an open licence to respond to emergencies, not a paid assignment, and not an active verified marshal credential.', status: 'FUTURE CONTRIBUTION', cta: 'Join as Independent Marshal', href: '/signup?role=Independent%20Marshal', faq: [['How is this different from a Group Marshal?', 'A Group Marshal contributes within a defined group. An Independent Marshal is a future cross-community pathway that still requires clear verification and scope.'], ['Can I respond on behalf of BBBT?', 'Not through this prototype. No public response authority or guaranteed coverage is granted by applying.']] },
  'founding-rider-council': { title: 'Founding Rider Council', eyebrow: 'Experience, testing and governance', intro: 'The Founding Rider Council is a contribution layer for experienced riders who want to challenge assumptions, test ideas and help shape accountable standards.', imageAlt: 'Conceptual rider council discussion around maps and safety notes; not a verified BBBT council meeting.', benefits: ['Contribute field experience to future safety systems', 'Review concepts and challenge weak assumptions', 'Participate in controlled testing and feedback', 'Help protect rider dignity, privacy and practical value'], responsibilities: ['Offer evidence-based, constructive feedback', 'Separate personal preference from shared safety standards', 'Respect the Trust and Holding distinction', 'Understand that contribution is not ownership or governance control'], notThis: 'Not an ownership claim, investment product, elected authority or promise of paid work.', status: 'PARTIAL PATHWAY', cta: 'Join the Founding Council', href: '/signup?role=Founding%20Rider%20Council%20Member', faq: [['Who is the Council for?', 'Experienced riders and contributors who can bring practical road knowledge, testing discipline and honest feedback.'], ['Does joining create ownership?', 'No. The Council is a contribution layer. Participation does not create equity, ownership or a financial claim.']] },
}

export default async function RolePage({ params }: { params: Promise<{ role: string }> }) {
  const data = content[(await params).role]
  if (!data) notFound()
  return <main className="pp role-brief-page"><Hero label={data.eyebrow} title={data.title} lede={data.intro} image={{ src: '/images/role-brief-rider.png', alt: data.imageAlt }}><StatusBadge>{data.status}</StatusBadge><Cta href={data.href}>{data.cta}</Cta></Hero><section className="pp-section"><div className="role-brief-grid"><article className="role-brief-panel"><span className="pp-card-kicker">WHAT YOU CAN EXPECT</span><h2>What this role gets</h2><ul>{data.benefits.map((item) => <li key={item}>{item}</li>)}</ul></article><article className="role-brief-panel"><span className="pp-card-kicker">WHAT YOU AGREE TO</span><h2>Responsibilities</h2><ul>{data.responsibilities.map((item) => <li key={item}>{item}</li>)}</ul></article></div><div className="role-brief-boundary"><strong>Important boundary</strong><p>{data.notThis}</p></div><ResponsibilityNotice /></section><section className="pp-section pp-section--alt"><div className="pp-head"><p className="section-label">Questions before choosing</p><h2>{data.title} FAQ</h2></div><FAQList items={data.faq} /><div className="role-brief-links"><Cta href={data.href}>{data.cta}</Cta><a className="pp-route__go" href="/about">Back to What is BBBT <ChevronRight size={15} /></a></div></section></main>
}
