'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Camera, Check, FileText, ImagePlus, Plus, Save, ShieldCheck, Trash2, Upload, UserRound } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

type Bike = { number: string; brand: string; model: string; modelNo: string; year: string; fullPhoto?: string; fullPhotoPath?: string; meterPhoto?: string; meterPhotoPath?: string }

const emptyBike = (): Bike => ({ number: '', brand: '', model: '', modelNo: '', year: '' })

export default function RiderProfilePage() {
  const [supabase] = useState(() => typeof window === 'undefined' ? null : createClient())
  const [userId, setUserId] = useState<string>()
  const [profile, setProfile] = useState<string>()
  const [profilePath, setProfilePath] = useState<string>()
  const [report, setReport] = useState<string>()
  const [reportPath, setReportPath] = useState<string>()
  const [saved, setSaved] = useState(false)
  const [bikes, setBikes] = useState<Bike[]>([{ number: 'KA 05 MX 0721', brand: 'Royal Enfield', model: 'Classic 350', modelNo: 'J1-350', year: '2022' }])
  useEffect(() => { if (!supabase) return; (async () => { const { data: { user } } = await supabase.auth.getUser(); if (!user) return; setUserId(user.id); const [{ data: rider }, { data: bikeRows }] = await Promise.all([supabase.from('rider_profiles').select('avatar_path,blood_report_path').eq('id', user.id).maybeSingle(), supabase.from('rider_bikes').select('*').eq('rider_id', user.id).order('created_at')]); if (rider?.avatar_path) { setProfilePath(rider.avatar_path); const { data } = await supabase.storage.from('rider-vault').createSignedUrl(rider.avatar_path, 3600); setProfile(data?.signedUrl) } if (rider?.blood_report_path) { setReportPath(rider.blood_report_path); const { data } = await supabase.storage.from('rider-vault').createSignedUrl(rider.blood_report_path, 3600); setReport(data?.signedUrl) } if (bikeRows?.length) setBikes(bikeRows.map((b) => ({ number: b.registration_number, brand: b.brand || '', model: b.model || '', modelNo: b.model_number || '', year: b.model_year?.toString() || '', fullPhoto: b.full_bike_photo_path, fullPhotoPath: b.full_bike_photo_path, meterPhoto: b.console_photo_path, meterPhotoPath: b.console_photo_path }))) })() }, [])
  const updateBike = (index: number, key: keyof Bike, value: string) => setBikes((items) => items.map((bike, i) => i === index ? { ...bike, [key]: value } : bike))
  const upload = async (file: File | undefined, callback: (url: string) => void, pathCallback?: (path: string) => void) => { if (!file || !userId || !supabase) return; const allowed = ['image/jpeg', 'image/png', 'image/webp', 'application/pdf']; const max = file.type === 'application/pdf' ? 10 * 1024 * 1024 : 5 * 1024 * 1024; if (!allowed.includes(file.type) || file.size > max) { window.alert(`Please choose a JPG, PNG, WEBP${file.type === 'application/pdf' ? ' or PDF' : ''} under ${file.type === 'application/pdf' ? '10' : '5'} MB.`); return } const header = new Uint8Array(await file.slice(0, 12).arrayBuffer()); const starts = (bytes: number[]) => bytes.every((value, index) => header[index] === value); const validSignature = file.type === 'image/jpeg' ? starts([0xff, 0xd8, 0xff]) : file.type === 'image/png' ? starts([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]) : file.type === 'image/webp' ? starts([0x52, 0x49, 0x46, 0x46]) && header[8] === 0x57 && header[9] === 0x45 && header[10] === 0x42 && header[11] === 0x50 : starts([0x25, 0x50, 0x44, 0x46, 0x2d]); if (!validSignature) { window.alert('This file signature does not match its selected type. Please choose a real image or PDF.'); return } const path = `${userId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, '')}`; const { error } = await supabase.storage.from('rider-vault').upload(path, file, { upsert: false, contentType: file.type }); if (error) return; const { data } = await supabase.storage.from('rider-vault').createSignedUrl(path, 3600); if (data?.signedUrl) callback(data.signedUrl); pathCallback?.(path) }
  const exportData = () => { const payload = { profile: { profilePath, reportPath }, bikes: bikes.map(({ fullPhoto, meterPhoto, ...bike }) => bike), exportedAt: new Date().toISOString() }; const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'bbbt-rider-data.json'; anchor.click(); URL.revokeObjectURL(url) }
  const deleteVault = async () => { if (!userId || !supabase || !window.confirm('Delete your BBBT rider data and uploaded files? This cannot be undone.')) return; const paths = [profilePath, reportPath, ...bikes.flatMap((bike) => [bike.fullPhotoPath, bike.meterPhotoPath])].filter(Boolean) as string[]; if (paths.length) await supabase.storage.from('rider-vault').remove(paths); await supabase.from('rider_bikes').delete().eq('rider_id', userId); await supabase.from('rider_profiles').delete().eq('id', userId); setProfile(undefined); setReport(undefined); setBikes([]); setSaved(false) }
  return <main className="dashboard-shell reference-dashboard profile-page">
    <header className="dashboard-topbar"><Link href="/dashboard/soscore" className="dash-home"><ArrowLeft size={15} /> BACK TO DASHBOARD</Link><span className="dash-status">RIDER VAULT / SECURE STORAGE</span></header>
    <div className="profile-wrap">
      <div className="profile-heading"><div><span className="eyebrow cyan-text">RIDER IDENTITY / 07</span><h1>Rider <span>Profile</span></h1><p>Keep your safety identity, medical document and bike records ready for the BBBT network.</p></div><div className="profile-security"><ShieldCheck size={18} /><span>PRIVATE VAULT<br /><b>PRIVATE / SIGNED URL</b></span></div></div>
      <div className="profile-grid">
        <section className="profile-card identity-card"><div className="card-kicker">01 / RIDER IDENTITY</div><div className="identity-content"><div className="avatar-upload" style={profile ? { backgroundImage: `url(${profile})` } : undefined}><UserRound size={38} /><label title="Upload profile photo"><Camera size={15} /><input type="file" accept="image/*" capture="user" onChange={(e) => upload(e.target.files?.[0], setProfile, setProfilePath)} /></label></div><div className="identity-copy"><h2>Arjun Singh</h2><p>BBBT RIDER / BENGALURU NODE 07</p><span className="verified"><Check size={13} /> PROFILE READY</span></div></div><div className="upload-hint"><ImagePlus size={15} /><span>Profile picture<br /><small>Gallery or direct camera capture</small></span><label className="mini-upload">UPLOAD<input type="file" accept="image/*" capture="user" onChange={(e) => upload(e.target.files?.[0], setProfile, setProfilePath)} /></label></div></section>
        <section className="profile-card medical-card"><div className="card-kicker">02 / MEDICAL READY</div><div className="blood-highlight"><strong>O+</strong><span>PRIMARY BLOOD GROUP<br /><b>EMERGENCY VISIBLE</b></span></div><div className="report-upload"><FileText size={19} /><div><b>{report ? 'Latest report attached' : 'Latest blood report'}</b><small>{report ? 'Ready for manual verification' : 'PDF, JPG or PNG · max 10 MB'}</small></div><label className="mini-upload"><Upload size={13} /> ADD<input type="file" accept="image/*,.pdf" onChange={(e) => upload(e.target.files?.[0], setReport, setReportPath)} /></label></div><div className="prototype-note">Private upload — stored in your rider vault. Medical documents are not verified by BBBT.</div></section>
      </div>
      <section className="profile-card bikes-section"><div className="section-head"><div><div className="card-kicker">03 / MOTORCYCLE GARAGE</div><h2>Your <span>Bikes</span> <small>{bikes.length} / 3 SLOTS</small></h2><p>Add up to three bikes. Each bike needs one full photo showing the number plate and one clear console-meter photo showing kilometres.</p></div>{bikes.length < 3 && <button className="outline-action" onClick={() => setBikes([...bikes, emptyBike()])}><Plus size={15} /> ADD BIKE</button>}</div><div className="bike-list">{bikes.map((bike, index) => <article className="bike-record" key={index}><div className="bike-number"><span>BIKE 0{index + 1}</span><strong>{bike.number || 'REGISTRATION PENDING'}</strong>{index > 0 && <button onClick={() => setBikes(bikes.filter((_, i) => i !== index))} aria-label="Remove bike"><Trash2 size={14} /></button>}</div><div className="bike-fields"><label>BIKE NUMBER<input value={bike.number} placeholder="KA 05 XX 0000" onChange={(e) => updateBike(index, 'number', e.target.value)} /></label><label>BRAND<input value={bike.brand} placeholder="Royal Enfield" onChange={(e) => updateBike(index, 'brand', e.target.value)} /></label><label>MODEL NAME<input value={bike.model} placeholder="Classic 350" onChange={(e) => updateBike(index, 'model', e.target.value)} /></label><label>MODEL NUMBER<input value={bike.modelNo} placeholder="J1-350" onChange={(e) => updateBike(index, 'modelNo', e.target.value)} /></label><label>MODEL YEAR<input value={bike.year} placeholder="2022" onChange={(e) => updateBike(index, 'year', e.target.value)} /></label></div><div className="bike-uploads"><UploadTile title="FULL BIKE PHOTO" hint="Show complete bike + number plate" value={bike.fullPhoto} onChange={(file) => upload(file, (url) => updateBike(index, 'fullPhoto', url), (path) => updateBike(index, 'fullPhotoPath', path))} /><UploadTile title="CONSOLE METER PHOTO" hint="Show odometer / KM clearly" value={bike.meterPhoto} onChange={(file) => upload(file, (url) => updateBike(index, 'meterPhoto', url), (path) => updateBike(index, 'meterPhotoPath', path))} /></div></article>)}</div></section>
      <div className="profile-footer"><span><ShieldCheck size={14} /> PRIVATE SUPABASE VAULT · SIGNED ACCESS</span><div className="vault-controls"><button className="outline-action" type="button" onClick={exportData}>EXPORT DATA</button><button className="outline-action danger-action" type="button" onClick={deleteVault}>DELETE MY DATA</button><button className="btn btn-cyan" onClick={async () => { if (!userId || !supabase) return; await supabase.from('rider_profiles').upsert({ id: userId, avatar_path: profilePath, blood_report_path: reportPath, blood_group: 'O+', updated_at: new Date().toISOString() }); await Promise.all(bikes.filter((bike) => bike.number).map((bike) => supabase.from('rider_bikes').upsert({ rider_id: userId, registration_number: bike.number, brand: bike.brand || null, model: bike.model || null, model_number: bike.modelNo || null, model_year: bike.year ? Number(bike.year) : null, full_bike_photo_path: bike.fullPhotoPath || null, console_photo_path: bike.meterPhotoPath || null }))); setSaved(true); setTimeout(() => setSaved(false), 2200) }}><Save size={15} /> {saved ? 'PROFILE SAVED' : 'SAVE PROFILE'}</button></div></div>
    </div>
  </main>
}

function UploadTile({ title, hint, value, onChange }: { title: string; hint: string; value?: string; onChange: (file: File) => void }) { return <label className={`upload-tile ${value ? 'has-image' : ''}`} style={value?.startsWith('http') ? { backgroundImage: `linear-gradient(rgba(3,8,9,.2),rgba(3,8,9,.75)),url(${value})` } : undefined}><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => { if (e.target.files?.[0]) onChange(e.target.files[0]) }} />{value ? <span><Check size={15} /> PHOTO ATTACHED</span> : <><ImagePlus size={20} /><b>{title}</b><small>{hint}</small></>}</label> }
