import { Hero } from '@/components/public-site'

export const metadata = {
  title: 'Privacy | BBBT Trust',
  description: 'Prototype privacy information for BBBT Trust.',
  alternates: { canonical: '/privacy' },
}

export default function Page() {
  return <main className="legal-page"><Hero label="Legal / Privacy" title="Privacy is part of trust." lede="This page describes how information may be handled across the BBBT public prototype. It is not a final production privacy policy."><p className="legal-notice">Prototype notice: planned features, forms, and account flows may change before any production launch.</p></Hero><section className="page-content legal-content"><h2>About BBBT</h2><p>BBBT Trust is being designed as a safety, emergency-support, community, and rider-welfare layer for India&apos;s riding communities.</p><h2>Information that may be collected</h2><p>When you use signup, contact, or other prototype systems, BBBT may receive information you choose to provide, such as your name, email, mobile number, address, rider profile, vehicle details, emergency-contact details, community role, and the content of your request. Safety-related information, including rider-provided incident context or blood-support preferences, should only be shared when relevant and with your consent.</p><h2>Why information may be used</h2><p>Information may be used to review and route contact requests, understand rider and community needs, support prototype account or profile flows, improve the proposed ecosystem, communicate about your request, and maintain safety-focused records where applicable.</p><h2>Consent and control</h2><p>Only provide information you are comfortable sharing and that is relevant to the purpose. You may contact BBBT to ask what information was submitted, request correction, or ask a question about its handling. Prototype screens do not create a promise of a future service or response.</p><h2>Retention and security principles</h2><p>BBBT intends to retain information only for as long as reasonably needed for the stated prototype purpose or an applicable legal need, then review whether it should be deleted. Access should be limited to people who need it for review or routing, and reasonable safeguards should be applied. This prototype does not claim a particular certification, encryption standard, or production security infrastructure.</p><h2>Sharing and disclosure</h2><p>BBBT does not sell submitted information. Information may be shared when needed to review or route a request, when you ask BBBT to involve a community or partner, or when disclosure is required by law. Any future production partners and data practices will be described in an updated policy before launch.</p><h2>Prototype versus production</h2><p>This notice reflects the current public prototype, not a final policy for a launched emergency, membership, or partner network. Future production systems may require more specific notices, consent choices, retention rules, and user controls.</p><h2>Privacy questions</h2><p>For privacy questions, use the <a href="/contact">Contact BBBT</a> route or email <a href="mailto:connect@bbbt.in">connect@bbbt.in</a>.</p></section></main>
}
