'use client'

import Link from 'next/link'
import { ArrowRight, HeartPulse, MapPinned, ShieldCheck, Siren, Users, Radio, Route, GraduationCap, Building2, Landmark, ChevronRight, Bike, Network, Crown, BarChart3, AlertTriangle, CheckCircle2, LifeBuoy } from 'lucide-react'
import { Cta, FeatureCard, SectionLabel, Shell, StatusBadge, FAQList, faqItems } from '@/components/public-site'

const layers=['SOS / Emergency Queues','Blood & Hospital Mesh','Safety, Training & Kit','Navigation & Corridor Scan','Democratic Governance & Trust Matrix','Regional Marshal Network','Care Pit Commerce','Training & Certification','Infrastructure Audits','The Trust Protocol']
const pillars=[['SOS & Emergency',Siren,'Future response framework'],['Care Pit Network',Building2,'Verified route support'],['Safety Training',GraduationCap,'Readiness and education'],['Route & Corridor Support',Route,'Highway intelligence'],['Verified Rider Network',ShieldCheck,'Trust-led participation']]

export default function Home(){return <Shell><main>
<section className="hero hero-home"><div className="hero-copy"><SectionLabel>BBBT / Brand Biker Brotherhood Trust</SectionLabel><h1>India&apos;s rider <em>safety infrastructure.</em></h1><p>BBBT is building a trusted safety, emergency-response, community and highway-support infrastructure for riders across India.</p><p className="positioning"><strong>BBBT is not a social network.</strong> It is designed around rider safety, emergency readiness, verified human networks, highway support, training, governance and community intelligence.</p><div className="hero-actions"><Cta href="#join">Join the rider network</Cta><Link className="button" href="/how-it-works">Explore the BBBT protocol <ArrowRight aria-hidden="true"/></Link></div><StatusBadge>Prototype / Pre-launch</StatusBadge></div><div className="hero-visual" role="img" aria-label="Indian touring rider travelling on a highway"><div className="route-overlay"><span>ROAD</span><ArrowRight/><span>RIDER</span><ArrowRight/><span>NETWORK</span><ArrowRight/><span>SAFETY</span></div></div></section>
<section id="join" className="section entry-section"><div className="section-heading"><SectionLabel>Choose your entry point</SectionLabel><h2>One infrastructure layer. Five ways to participate.</h2><p>Start with the role that fits your relationship with the road. There is no payment or live emergency coverage in this prototype.</p></div><div className="audience-grid"><Entry icon={Bike} title="Rider" text="Build your safety identity, emergency profile and bike profile." href="/rider-signup" cta="Create rider profile"/><Entry icon={Users} title="Group Admin" text="Bring your riding community into a structured safety network." href="/community" cta="Bring your group"/><Entry icon={ShieldCheck} title="Marshal" text="Support rider safety and organised ride operations." href="/safety" cta="Explore marshal role"/><Entry icon={Crown} title="Founding Rider Council" text="Contribute rider intelligence, education, testing and expertise." href="/founding-rider-council" cta="Explore the council"/><Entry icon={BarChart3} title="Investor" text="Explore the network, architecture and future commercial layer." href="/investor" cta="View investor brief"/></div></section>
<section className="section ecosystem-section"><div className="section-heading"><SectionLabel>The BBBT ecosystem</SectionLabel><h2>Trust at the centre of the road.</h2><p>Two connected but distinct layers. The Trust serves rider welfare; the Holding carries future commercial products and technology.</p></div><div className="ecosystem-diagram"><div className="ecosystem-orbit">{['Rider Safety','SOS & Emergency','Blood & Hospital Mesh','Care Pit Network','Highway Corridor','Marshal Network','Safety Training','Rider Governance','Founding Rider Council','Rider Community'].map(x=><span key={x}>{x}</span>)}</div><div className="ecosystem-core"><strong>BBBT Trust</strong><small>Safety · Community · Governance · Rider Welfare</small></div></div><div className="holding-card"><span className="section-label">Separate commercial layer</span><strong>BBBT Holding</strong><span>Commercial · Products · Technology · BBBT Shop</span></div></section>
<section className="section"><div className="section-heading"><SectionLabel>Built for the road</SectionLabel><h2>Operational pillars, not social features.</h2></div><div className="feature-grid">{pillars.map(([title,Icon,text])=><FeatureCard key={title as string} title={title as string} icon={Icon as typeof ShieldCheck} status="Planned" accent="teal">{text as string}</FeatureCard>)}</div></section>
<section className="section road-scenario"><div className="section-heading"><SectionLabel>Prototype workflow</SectionLabel><h2>From a ride problem to a coordinated safety response.</h2><p>BBBT is designed to connect the rider, trusted people and planned highway-support infrastructure around a common safety workflow.</p></div><div className="road-flow" aria-label="Prototype workflow: ride, problem, SOS or alert, verified network, Care Pit or support"><FlowStep icon={Bike} label="RIDE"/><b aria-hidden="true">→</b><FlowStep icon={AlertTriangle} label="PROBLEM"/><b aria-hidden="true">→</b><FlowStep icon={Siren} label="SOS / ALERT"/><b aria-hidden="true">→</b><FlowStep icon={Network} label="VERIFIED NETWORK"/><b aria-hidden="true">→</b><FlowStep icon={LifeBuoy} label="CARE PIT / SUPPORT"/></div></section>
<section className="section protocol-section"><div className="section-heading"><SectionLabel>Trust protocol</SectionLabel><h2>10 layers of accountable infrastructure.</h2></div><div className="protocol-list">{layers.map((layer,i)=><div className="protocol-row" key={layer}><span>{String(i+1).padStart(2,'0')}</span><strong>{layer}</strong><ChevronRight aria-hidden="true"/></div>)}</div></section>
<section className="section comparison-section"><div className="section-heading"><SectionLabel>Why BBBT</SectionLabel><h2>Infrastructure that works with rider communities.</h2></div><div className="comparison-grid"><div><h3>Traditional communities</h3><p>Information and support can be fragmented, informal and difficult to coordinate during a long-distance emergency.</p><ul><li>Scattered emergency contacts</li><li>Informal support pathways</li><li>No shared safety identity</li><li>Limited corridor infrastructure</li></ul></div><div className="comparison-bbbt"><h3>BBBT layer</h3><p>A structured complement to the communities riders already trust.</p><ul><li>Safety identity and readiness</li><li>Verified human networks</li><li>Care Pit infrastructure</li><li>Training, governance and intelligence</li></ul></div></div></section>
<section className="section prototype-section"><StatusBadge>Prototype / Pre-launch</StatusBadge><h2>Designed to be honest about what is not live.</h2><p>BBBT is currently in prototype development. Some network, emergency and infrastructure views are simulations designed to demonstrate the intended operating model.</p><strong>Prototype data must not be interpreted as live emergency-service availability.</strong></section>
<section className="section cta-stack"><Cta href="/rider-signup">Register as a rider</Cta><h2>Your road. Your identity. Your safety network.</h2><p>Register your interest and help us understand where India&apos;s riders are ready for structured safety infrastructure.</p><div className="cta-row"><Link className="button" href="/community">Register as Group Admin <ArrowRight/></Link><Link className="button" href="/founding-rider-council">Explore Founding Rider Council <ArrowRight/></Link><Link className="button" href="/investor">Investor Preview <ArrowRight/></Link></div></section>
<section className="section voice-section"><div><SectionLabel>BBBT Voice Assistant</SectionLabel><h2>Navigate the prototype in your language.</h2><p>A planned voice interface to help users find BBBT information and prototype sections. It does not provide medical advice or dispatch emergency services.</p></div><div className="voice-status"><Radio aria-hidden="true"/><span>Assistant concept</span><StatusBadge>Planned</StatusBadge></div></section>
<section className="section faq-section"><div className="section-heading"><SectionLabel>Questions riders ask</SectionLabel><h2>Clear before you join.</h2></div><FAQList items={faqItems}/></section>
</main></Shell>}
function Entry({icon:Icon,title,text,href,cta}:{icon:React.ComponentType<{ 'aria-hidden'?: boolean }>,title:string,text:string,href:string,cta:string}){return <Link className="audience-card" href={href}><div className="audience-icon"><Icon aria-hidden={true}/></div><SectionLabel>Entry point</SectionLabel><h3>{title}</h3><p>{text}</p><span>{cta} <ArrowRight aria-hidden="true"/></span></Link>}
function FlowStep({icon:Icon,label}:{icon:React.ComponentType<{ 'aria-hidden'?: boolean }>,label:string}){return <span className="flow-step"><Icon aria-hidden={true}/><strong>{label}</strong></span>}
export { HeartPulse, MapPinned, Users }
