'use client'

import { useState } from 'react'
import Link from 'next/link'
import { ArrowRight, Battery, Check, ChevronRight, Cross, MapPin, Radio, Siren, ShieldCheck, UserRound, Zap } from 'lucide-react'
import { BBBTAssistant } from '@/components/bbbt-assistant'
import RouteMap from '@/components/route-map'

type Mode = 'sos' | 'blood' | 'route'

const nav = [
  { id: 'sos' as Mode, label: 'SOS Core', href: '/dashboard/soscore', icon: Siren },
  { id: 'blood' as Mode, label: 'Blood Mesh', href: '/dashboard/bloodmesh', icon: Cross },
  { id: 'route' as Mode, label: 'Route Corridor', href: '/dashboard/routecorridor', icon: MapPin },
]

export default function BBBTDashboard({ mode }: { mode: Mode }) {
  const [active, setActive] = useState(mode)
  const [running, setRunning] = useState(false)
  const [selected, setSelected] = useState('O+')
  const [notice, setNotice] = useState('')
  const current = nav.find((item) => item.id === active) ?? nav[0]

  const simulate = (message: string) => { setNotice(message); setRunning(true); window.setTimeout(() => setRunning(false), 2600) }

  return <div className="dashboard-shell reference-dashboard">
    <header className="dashboard-topbar"><Link href="/" className="brand"><span className="brand-mark">BB</span><span className="brand-wordmark" aria-label="BBBT"><b>BB</b><i>BT</i></span></Link><div className="dash-status"><span className="live-dot" /> NETWORK ONLINE / NODE 07—IND</div><div className="dashboard-actions"><Link href="/dashboard/profile" className="dash-profile"><UserRound size={14} /> RIDER PROFILE</Link><Link href="/" className="dash-home">Back to protocol <ArrowRight size={14} /></Link></div></header>
    <div className="demo-status"><span className="live-dot cyan-dot" /> INVESTOR DEMO / LOCAL SIMULATION <span>NO REAL DISPATCH OR MEDICAL VERIFICATION</span></div><main className="dashboard-main">
      <aside className="dashboard-sidebar"><span className="eyebrow">COMMAND CENTER / 01</span><h1>Rider safety<br /><span>infrastructure.</span></h1><p>One network. Three critical systems. Built for the moment everything else fails.</p><nav className="dash-nav">{nav.map(({ id, label, href, icon: Icon }) => <Link key={id} href={href} onClick={() => setActive(id)} className={`dash-nav-item ${active === id ? 'active' : ''}`}><Icon size={17} /><span><b>{label}</b><small>{id === 'sos' ? 'Emergency response' : id === 'blood' ? 'Verified care network' : 'Live highway scan'}</small></span><ChevronRight size={15} /></Link>)}</nav><div className="sidebar-foot"><ShieldCheck size={16} /><span>All nodes are verified<br />before entering the mesh.</span></div></aside>
      <section className="dashboard-content"><div className="dash-heading"><div><span className={`eyebrow ${active === 'sos' ? 'red-text' : 'cyan-text'}`}><span className="live-dot" /> PRIORITY 0{active === 'sos' ? '1' : active === 'blood' ? '2' : '4'} / LIVE</span><h2>{current.label}<br /><span>{active === 'sos' ? 'emergency queue.' : active === 'blood' ? 'care network.' : 'scan active.'}</span></h2></div><div className="dash-clock"><b>12:41:08</b><span>FRI 14 JUN / IST</span></div></div>
        {active === 'sos' && <SOS running={running} notice={notice} simulate={simulate} />}
        {active === 'blood' && <Blood selected={selected} setSelected={setSelected} notice={notice} simulate={simulate} />}
        {active === 'route' && <Route notice={notice} simulate={simulate} />}
      </section>
    </main>
  </div>
}

function SOS({ running, notice, simulate }: { running: boolean; notice: string; simulate: (s: string) => void }) { return <><div className="rider-strip"><div className="rider-avatar">RS</div><div><b>RIDER STATUS / ARJUN SINGH</b><small>O+ BLOOD GROUP · SAFETY KIT VERIFIED · LAST SYNC 12:41</small></div><span className="online-pill"><span className="live-dot" /> ONLINE</span></div><div className="mode-tabs"><button className="active">SOS CORE</button><Link href="/dashboard/routecorridor">ROUTE CORRIDOR</Link><span>NODE 07 / BENGALURU</span></div><div className={`sos-console ${running ? 'engaged' : ''}`}><div className="console-top"><span><span className="live-dot" /> SOS CONSOLE / HOLD TO ACTIVATE</span><span>FALLBACK: QR + PHYSICAL CARD</span></div><button className="sos-trigger" onPointerDown={() => simulate('SOS signal transmitted. 4 responders are moving to your location.')} onClick={() => simulate('SOS signal transmitted. 4 responders are moving to your location.')}><Siren size={34} /><strong>{running ? 'SIGNAL SENT' : 'HOLD / SEND SOS'}</strong><small>{running ? 'DISPATCH QUEUE ACTIVE' : 'Emergency signal to verified riders'}</small></button><div className="console-foot"><span>ROUTE <b>CONFIRMED</b></span><span>ETA <b>04:12</b></span><span>RESPONDERS <b>04</b></span></div></div><div className="dash-grid"><div className="dash-panel"><div className="panel-title">RESPONSE TIMELINE <span>LIVE</span></div>{['SOS route authenticated', 'South Zone marshal notified', 'Nearest Care Pit acknowledged', 'Ambulance fallback channel ready'].map((x, i) => <div className="timeline-row" key={x}><span className={i < (running ? 4 : 2) ? 'done' : ''}>{i < (running ? 4 : 2) ? <Check size={13} /> : i + 1}</span><b>{x}</b><small>{i < 2 || running ? 'CONFIRMED' : 'STANDBY'}</small></div>)}</div><div className="dash-panel telemetry"><div className="panel-title">SIGNAL TELEMETRY</div><div className="signal-bars">{[1,2,3,4,5,6,7,8,9,10,11,12].map((x) => <i key={x} className={x < (running ? 12 : 9) ? 'on' : ''} />)}</div><b>{running ? 'TRANSMISSION LOCKED' : 'READY TO TRANSMIT'}</b><small>Encrypted emergency packet / 128-bit</small></div></div><div className="sos-stat-row"><div><small>EMERGENCY RADIUS</small><b>25 KM</b><span>4 care nodes reachable</span></div><div><small>NEAREST CARE PIT</small><b>2.8 KM</b><span>St. John Trauma Centre</span></div><div><small>NETWORK HEALTH</small><b className="green-text">96%</b><span>all channels verified</span></div></div><div className="emergency-actions"><button onClick={() => simulate('Prototype call flow opened for national emergency number 112.')}><Radio size={15} /> CALL 112</button><button onClick={() => simulate('Live location packet ready to share.')}><MapPin size={15} /> SHARE LOCATION</button><button onClick={() => simulate('Medical card opened: O+ blood group, emergency contact verified.')}><Cross size={15} /> MEDICAL CARD</button></div>{notice && <div className="dash-notice red-text">{notice}</div>}</> }

function Blood({ selected, setSelected, notice, simulate }: { selected: string; setSelected: (s: string) => void; notice: string; simulate: (s: string) => void }) { const hospitals = [['St. John Trauma Centre', '2.8 km', 'O+ / O−', '04 min'], ['Narayana Health City', '8.4 km', 'A+ / B+', '11 min'], ['Victoria Hospital Node', '12.1 km', 'All groups', '18 min']]; return <><div className="mesh-hero"><div className="mesh-visual"><div className="mesh-orbit orbit-1" /><div className="mesh-orbit orbit-2" /><span className="mesh-center"><Cross size={25} /><b>LIVE<br />MESH</b></span>{[1,2,3,4,5].map((n) => <i key={n} className={`mesh-pin mp-${n}`} />)}</div><div><span className="eyebrow cyan-text">VERIFIED MATCHING / 128 NODES</span><p className="mesh-lead">A living care network that routes blood, riders and hospital capacity before the call becomes a crisis.</p><div className="blood-chips">{['O+', 'O−', 'A+', 'B+', 'AB+'].map((x) => <button key={x} className={selected === x ? 'selected' : ''} onClick={() => setSelected(x)}>{x}</button>)}</div><button className="btn btn-cyan" onClick={() => simulate(`Searching verified ${selected} donors within 25 km...`)}><Radio size={16} /> Find a match</button></div></div><div className="panel-title hospital-title">NEAREST VERIFIED CARE NODES <span>3 ONLINE</span></div><div className="hospital-grid">{hospitals.map(([name, distance, blood, eta]) => <button className="hospital-card" key={name} onClick={() => simulate(`${name} selected. Dispatch request queued.`)}><div><span className="hospital-pulse" /><b>{name}</b></div><small>{blood} compatible</small><div className="hospital-meta"><span><MapPin size={13} /> {distance}</span><strong>{eta} ETA</strong></div></button>)}</div>{notice && <div className="dash-notice cyan-text">{notice}</div>}</> }

function Route({ notice, simulate }: { notice: string; simulate: (s: string) => void }) { const [rideMode, setRideMode] = useState(false); return <><div className="ride-mode-bar"><div><b>RIDE START SAFETY MODE</b><small>Location consent · route watch · nearby Care Pit alerts</small></div><button className={`btn ${rideMode ? 'btn-green' : 'btn-cyan'}`} onClick={() => { setRideMode(!rideMode); simulate(rideMode ? 'Ride mode paused. Your location watch is off.' : 'Ride mode active. Corridor watch and SOS voice phrase are ready.') }}>{rideMode ? 'ACTIVE / STOP' : 'START RIDE'}</button></div><div className="route-map real-map-frame"><RouteMap /><div className="route-readout"><span>ROUTE CONFIDENCE</span><b>96%</b><small>OSM LIVE TILES / 4 RIDERS</small></div></div><div className="waypoint-grid">{[['CARE PIT 01', '42 KM', 'OPEN', 'green'], ['MARSHAL NODE', '67 KM', '2 RIDERS', 'cyan'], ['TRAUMA OUTPOST', '91 KM', 'ALERT', 'red']].map(([name, km, status, tone]) => <button key={name} className="waypoint-card" onClick={() => simulate(`${name} opened on corridor. Navigation packet ready.`)}><span className={`waypoint-status ${tone}`} /> <div><b>{name}</b><small>{km} from current position</small></div><strong>{status}</strong><ChevronRight size={15} /></button>)}</div>{notice && <div className="dash-notice cyan-text">{notice}</div>}</> }
function BikeIcon() { return <Battery size={14} /> }
