'use client'

import { useState } from 'react'
import Link from 'next/link'
import { AlertTriangle, ArrowRight, CheckCircle2, CloudRain, LocateFixed, Map, Mic, Navigation, Pause, Play, Radio, ShieldAlert, StopCircle, Users } from 'lucide-react'

type FeatureKey = 'navigation' | 'sos' | 'blood' | 'ride'

const featureCopy: Record<FeatureKey, { label: string; title: string; lede: string; status: string; visual: string; points: [string, string][]; faq: [string, string][] }> = {
  navigation: { label: 'NAVIGATION + WEATHER', title: 'Read the road before the road asks you to.', lede: 'A rider-facing route and weather concept for preparing the journey, spotting waypoints and making safer decisions before departure.', status: 'PROTOTYPE / DEMO DATA', visual: 'route', points: [['Route preview', 'A calm view of the intended corridor, waypoints and arrival sequence.'], ['Weather context', 'Weather states can inform preparation; no live provider is connected in this prototype.'], ['Journey progress', 'A future rider experience that keeps the next meaningful step visible.']], faq: [['Is this live navigation?', 'No. The route and weather shown here are clearly labelled demo states, not live traffic or current weather.'], ['Can I use this for emergency directions?', 'No. Use official local services and real navigation tools for live situations.']] },
  sos: { label: 'SOS + EMERGENCY', title: 'When something goes wrong, make the next step clear.', lede: 'A safety-first escalation concept that separates rider readiness from live emergency dispatch. This simulation never contacts emergency services.', status: 'SIMULATION / NOT DISPATCH', visual: 'sos', points: [['Ready before the ride', 'Prepare contacts and context before a critical moment.'], ['Location honestly', 'Browser location is requested only in the demo; denied location stays unavailable.'], ['Human support concept', 'Future marshals, Care Pits and care pathways are links or concepts until verified.']], faq: [['Does SOS contact help?', 'No. This prototype does not dispatch help, notify contacts or guarantee response. Call official services such as 112 in India.'], ['What happens to my location?', 'The demo only reads browser permission state. It does not fabricate coordinates or expose private data publicly.']] },
  blood: { label: 'BLOOD MESH', title: 'A consent-led support concept for critical moments.', lede: 'Blood Mesh explores how riders might understand a blood-support request without exposing private medical information or claiming hospital-grade matching.', status: 'PROTOTYPE / NO MEDICAL VERIFICATION', visual: 'blood', points: [['Profile context', 'A future rider may record their own information in an authorized account.'], ['Compatibility concept', 'The demo illustrates a request flow, not a medical match or donor dispatch.'], ['Privacy by design', 'Public visitors see no names, phone numbers, medical reports or private locations.']], faq: [['Is this hospital-grade matching?', 'No. Never treat this prototype as a substitute for hospital blood typing or cross-match.'], ['Are donors or hospitals connected?', 'No. No donor count, hospital partner or live dispatch is claimed here.']] },
  ride: { label: 'START RIDE', title: 'Begin with readiness. Keep the journey visible.', lede: 'A rider journey concept that starts with a clear state, keeps SOS accessible and ends deliberately. GPS remains unavailable unless your browser provides it.', status: 'WORKING PROTOTYPE / LOCAL STATE', visual: 'ride', points: [['READY → ACTIVE → PAUSED → ENDED', 'The demo uses real interface state without pretending to create a live ride record.'], ['Safety always visible', 'Navigation, weather, SOS and Blood Mesh remain available as labelled feature paths.'], ['No fabricated GPS', 'Location status reflects browser availability, never invented coordinates.']], faq: [['Does Start Ride track me?', 'Not in this public demo. It uses local UI state and does not claim a live ride or tracking service.'], ['Can I join as a rider?', 'Yes. Use Join BBBT to enter the existing Rider signup pathway.']] },
}

function Visual({ kind, active }: { kind: string; active?: boolean }) {
  if (kind === 'route') return <div className="fx-visual fx-route"><div className="fx-route-line"><i /><i /><i /><i /></div><div className="fx-route-card"><Map size={20} /><strong>DEMO CORRIDOR</strong><span>Waypoints → Arrival</span></div><div className="fx-weather"><CloudRain size={18} /><span>WEATHER · PROTOTYPE</span><b>Prepare for change</b></div></div>
  if (kind === 'sos') return <div className="fx-visual fx-sos"><ShieldAlert size={62} /><strong>SOS PROTOTYPE</strong><span>DOES NOT CONTACT REAL EMERGENCY SERVICES</span><div className="fx-sos-state">{active ? 'SOS ACTIVE · SIMULATION' : 'READY TO DEMO'}</div></div>
  if (kind === 'blood') return <div className="fx-visual fx-blood"><div><Users size={28} /><span>RIDER</span></div><ArrowRight /><div><Radio size={28} /><span>BLOOD MESH</span></div><ArrowRight /><div><LocateFixed size={28} /><span>SUPPORT CONCEPT</span></div><small>PROTOTYPE · CONSENT REQUIRED · NO MEDICAL MATCH</small></div>
  return <div className="fx-visual fx-ride"><div className="fx-ride-ring"><Navigation size={42} /><span>{active ? 'ACTIVE DEMO' : 'READY'}</span></div><strong>RIDE STATE</strong><small>LOCATION: {active ? 'UNAVAILABLE' : 'NOT REQUESTED'}</small></div>
}

export function FeatureExperience({ kind }: { kind: FeatureKey }) {
  const copy = featureCopy[kind]
  const [active, setActive] = useState(false)
  const [location, setLocation] = useState<'not-requested' | 'available' | 'unavailable'>('not-requested')
  const [openFaq, setOpenFaq] = useState<number | null>(null)
  const requestLocation = () => { if (!navigator.geolocation) return setLocation('unavailable'); navigator.geolocation.getCurrentPosition(() => setLocation('available'), () => setLocation('unavailable'), { enableHighAccuracy: false, timeout: 5000 }) }
  return <main className="fx-page fx-page--with-fixed-nav">
    <header className="fx-hero"><div><span className="fx-eyebrow">{copy.label} · {copy.status}</span><h1>{copy.title}</h1><p>{copy.lede}</p><div className="fx-actions"><Link className="fx-button fx-button--primary" href="/signup?role=Rider">JOIN BBBT <ArrowRight size={16} /></Link><Link className="fx-button" href="/faq">VIEW ALL FAQ</Link></div></div><Visual kind={copy.visual} active={active} /></header>
    <section className="fx-section"><span className="fx-eyebrow">WHAT IT IS / WHY IT MATTERS</span><h2>Useful structure without pretending the future is live.</h2><div className="fx-points">{copy.points.map(([title, body]) => <article key={title}><CheckCircle2 size={20} /><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="fx-section fx-section--panel"><span className="fx-eyebrow">PROTOTYPE EXPERIENCE</span><h2>See the state, then understand the boundary.</h2><div className="fx-demo">{kind === 'sos' && <><p><AlertTriangle size={18} /> This is a safe simulation. It does not contact anyone.</p><button className="fx-button fx-button--primary" onClick={() => setActive(!active)}>{active ? 'CANCEL SIMULATION' : 'START SOS SIMULATION'} <ShieldAlert size={16} /></button></>}{kind === 'ride' && <><div className="fx-state"><b>STATUS</b><strong>{active ? 'ACTIVE' : 'READY'}</strong><span>Start time: {active ? new Date().toLocaleTimeString() : '—'}</span><span>Location: {location === 'available' ? 'AVAILABLE' : location === 'unavailable' ? 'LOCATION NOT AVAILABLE' : 'NOT REQUESTED'}</span></div><div className="fx-actions"><button className="fx-button fx-button--primary" onClick={() => setActive(!active)}>{active ? 'END DEMO' : 'START RIDE DEMO'} {active ? <StopCircle size={16} /> : <Play size={16} />}</button><button className="fx-button" onClick={requestLocation}><LocateFixed size={16} /> CHECK LOCATION</button></div></>}{kind === 'blood' && <div className="fx-flow"><b>Blood group</b><ArrowRight /><b>Location</b><ArrowRight /><b>Compatible match concept</b><small>NO MEDICAL VERIFICATION · NO DONOR DISPATCH</small></div>}{kind === 'navigation' && <div className="fx-flow"><b>START</b><ArrowRight /><b>ROUTE PREVIEW</b><ArrowRight /><b>WAYPOINTS</b><ArrowRight /><b>ARRIVAL</b><small>DEMO ROUTE · NO LIVE TRAFFIC · WEATHER PROTOTYPE</small></div>}</div></section>
    <section className="fx-section"><span className="fx-eyebrow">CONNECTED PATHS · STATUS LABELLED</span><div className="fx-links"><Link href="/safety-guides">Navigation + Weather <span>PROTOTYPE LINK →</span></Link><Link href="/emergency">SOS + Emergency <span>SIMULATION →</span></Link><Link href="/dashboard/bloodmesh">Blood Mesh <span>AUTHORIZED PROTOTYPE →</span></Link><Link href="/care-pits">Care Pits <span>PROPOSED NETWORK →</span></Link><Link href="/assistant">Voice Assistant <span>PROTOTYPE →</span></Link></div></section>
    <section className="fx-section fx-section--faq"><span className="fx-eyebrow">FAQ / LIMITATIONS</span><h2>Clear answers before the next step.</h2>{copy.faq.map(([q, a], i) => <div className="fx-faq" key={q}><button aria-expanded={openFaq === i} onClick={() => setOpenFaq(openFaq === i ? null : i)}>{q}<span>+</span></button>{openFaq === i && <p>{a}</p>}</div>)}<Link className="fx-text-link" href="/faq">VIEW ALL FAQ <ArrowRight size={15} /></Link></section>
    <footer className="fx-footer"><h2>Explore BBBT carefully.</h2><p>Join the existing Rider pathway, or connect with BBBT if you represent a partner or service.</p><div className="fx-actions"><Link className="fx-button fx-button--primary" href="/signup?role=Rider">JOIN BBBT <ArrowRight size={16} /></Link><Link className="fx-button" href="/contact">CONNECT WITH BBBT</Link></div></footer>
  </main>
}

export function AssistantFeatureExperience() { return <FeatureExperience kind="ride" /> }
