'use client'

import Image from 'next/image'
import { FormEvent, useCallback, useEffect, useRef, useState } from 'react'
import { ArrowLeft, ArrowRight, Pause, Play } from 'lucide-react'
import { FAQList, SectionLabel, Shell, StatusBadge } from '@/components/public-site'

type Slide = { section: string; title: string; message: string; visual: string; source?: string; tag?: string }

const slides: Slide[] = [
  { section: '01 / OPEN', title: 'One Nation. One BBBT. Every Rider.', message: 'A proposed rider safety and community infrastructure layer for India — presented with the discipline of what exists, what is planned and what still needs proof.', visual: 'opening', tag: 'PUBLIC PROTOTYPE' },
  { section: '02 / HUMAN PROBLEM', title: 'When a rider needs help, what system connects the dots?', message: 'Road knowledge, community support, emergency context and welfare often live in separate chats, contacts and memories. The gap is coordination — not goodwill.', visual: 'problem', tag: 'PROBLEM SCALE' },
  { section: '03 / ROAD SAFETY', title: 'The safety burden is real. The answer cannot be a slogan.', message: 'India’s road-safety burden is a national operating context. BBBT does not claim to solve accidents; it explores a structured layer for readiness, participation and future verified support.', visual: 'safety-data', source: 'Source: MoRTH, Road Accidents in India reports · latest edition to be verified in diligence' },
  { section: '04 / TWO-WHEELER SCALE', title: 'A large mobility base creates a large coordination surface.', message: 'Domestic two-wheeler sales recovered from the pandemic trough to approximately 1.96 crore in FY2024–25. Sales are not active riders; they are a measurable market signal.', visual: 'sales-chart', source: 'Source: SIAM, FY2024–25 · domestic two-wheeler sales; definition is vehicles sold, not users' },
  { section: '05 / POST-COVID SIGNAL', title: 'Recovery creates a signal — not a made-up “rider culture” statistic.', message: 'The defensible story is disruption → recovery → mobility rebound → a larger opportunity for better safety and participation infrastructure. Strategic implication, not source-reported fact.', visual: 'recovery', tag: 'STRATEGIC INTERPRETATION' },
  { section: '06 / HIGHWAY OPPORTUNITY', title: 'More movement means more distributed support requirements.', message: 'National highway expansion, longer routes and distributed rider movement create the context for roadside readiness. BBBT locations and coverage are not claimed today.', visual: 'highway', source: 'Source: MoRTH infrastructure publications · network metrics require source-year verification' },
  { section: '07 / TOURING', title: 'Adventure needs safety management, skills and rescue readiness.', message: 'India’s adventure-tourism strategy recognises safety management, capacity building, rescue and communication as system needs. BBBT’s opportunity is adjacent — not proof of rider-count demand.', visual: 'tourism', source: 'Source: Ministry of Tourism / PIB strategy materials · public rider counts not available' },
  { section: '08 / MARKET SIGNAL', title: 'A third-party forecast shows adjacent willingness to spend.', message: 'The India motorbike riding-gear market is forecast by Grand View Research at US$817.7M in 2024 and US$1.2051B by 2030. BBBT does not own this market today.', visual: 'gear-chart', source: 'Source: Grand View Research, 2025 · third-party forecast; market definition and methodology apply' },
  { section: '09 / FRAGMENTATION', title: 'Rider, safety, community, emergency and care are disconnected surfaces.', message: 'BBBT’s thesis is to connect the surfaces without pretending that every service is live. The infrastructure must earn trust one verified capability at a time.', visual: 'fragmentation', tag: 'THESIS' },
  { section: '10 / WHAT BBBT IS', title: 'Rider → Identity → Community → Ride → Safety → Support.', message: 'BBBT is building a rider-focused safety, community and welfare infrastructure ecosystem. The product wedge is shared participation; the long-term ambition is verified support.', visual: 'flow' },
  { section: '11 / ECOSYSTEM', title: 'One accountable layer. Many participation pathways.', message: 'Riders, groups, rides, referrals, FRC, partners, Care Pits, products and future safety surfaces form a proposed ecosystem — each with a visible status.', visual: 'ecosystem' },
  { section: '12 / ACTUAL PRODUCT', title: 'There is a prototype you can walk through.', message: 'Current evidence includes universal signup, role selection, identity, review, dashboards, groups, rides, referrals and public discovery. This is prototype evidence — not production traction.', visual: 'product', tag: 'CURRENT PROTOTYPE' },
  { section: '13 / NETWORK FLOW', title: 'The network starts with a simple action: participate.', message: 'Create group → share link → signup/login → join → membership. Create ride → share link → join. Referral → registration → attribution. No traffic numbers are claimed.', visual: 'network' },
  { section: '14 / SAFETY JOURNEY', title: 'A safety journey is a chain of dependencies.', message: 'Start Ride, navigation, weather, SOS, emergency contacts, Blood Mesh and Care Pit are shown by status — working, prototype, dependency, proposed or future.', visual: 'journey' },
  { section: '15 / WHY BBBT', title: 'The defensible wedge is rider-first coordination.', message: 'Rider-first. Ecosystem-first. Community plus safety. Physical plus digital. Role-based participation. These are differentiators to prove, not claims of being first, largest or number one.', visual: 'differentiation', tag: 'THESIS TO PROVE' },
  { section: '16 / TRUST + COMMERCIAL', title: 'Trust and Holding must stay distinct.', message: 'BBBT Trust is the proposed community, safety, governance and welfare layer. A future commercial entity may carry products, technology and commercial infrastructure. The holding company is not yet incorporated.', visual: 'split', tag: 'PLANNED STRUCTURE · NOT INCORPORATED' },
  { section: '17 / BUILD MATRIX', title: 'The investor question is: what exists, what is partial and what happens next?', message: 'The current build matrix makes boundaries visible. It is designed to reduce diligence friction, not hide it.', visual: 'matrix' },
  { section: '18 / 24-MONTH BUILD', title: 'Foundation first. Validation before scale.', message: 'Year 1: foundation and R&D. Year 2: prototype hardening, controlled validation, safety testing and field preparation. Specific outcomes remain gates, not promises.', visual: 'roadmap', tag: 'PLANNED / FUTURE' },
  { section: '19 / YEAR 3–5', title: 'Commercialisation is a future operating plan.', message: 'Potential paths include BBBT Shop, products, partner infrastructure and a commercial Care Pit model — subject to evidence, entity formation, operations and legal review.', visual: 'commercial', tag: 'PLANNED / FUTURE' },
  { section: '20 / PROPOSED ASK', title: '₹1.5 crore proposed pre-seed ask.', message: 'A proposed 24-month allocation: 35% emergency kit R&D and tooling; 25% Care Pit technology R&D; 20% riding-gear prototyping; 12% certification/testing; 8% legal, patents and incorporation.', visual: 'allocation', tag: 'PROPOSED · NOT RAISED' },
  { section: '21 / CAPITAL UNLOCKS', title: 'Capital should buy evidence, not theatre.', message: 'Capital → engineering → prototype hardening → testing → certification → field validation → commercial readiness. No guaranteed outcome is implied.', visual: 'unlock' },
  { section: '22 / CONVERSATION', title: 'We have not finished the journey. We have built the foundation.', message: 'See what exists. Test the prototype. Challenge the assumptions. Help shape the next proof gates. Request controlled access — not an investment checkout.', visual: 'closing' },
]

const matrix = [['Signup', 'Working prototype', 'Role-based flow'], ['Shared Identity', 'Prototype', 'Cross-surface concept'], ['Groups / Rides', 'Prototype', 'Participation flows'], ['Referrals', 'Prototype foundation', 'Attribution model'], ['SOS / Blood Mesh', 'Concept / future', 'No live dispatch claim'], ['Navigation / Weather', 'Dependency', 'External providers required'], ['Care Pit', 'Proposed', 'Operations and verification required']]
const faqs: [string, string][] = [
  ['What problem is BBBT solving?', 'BBBT explores a structured safety, community and welfare layer for riders where support is currently fragmented across chats, contacts, memory and disconnected services.'],
  ['What exists today?', 'A public prototype with role pathways, signup, identity concepts, dashboards, group and ride flows, referrals and public discovery. No user, revenue or coverage metrics are claimed.'],
  ['What is future?', 'Nationwide coverage, emergency dispatch, blood and hospital networks, navigation/weather integrations, verified Care Pits, products and commercial infrastructure.'],
  ['How does BBBT make money?', 'The current deck presents monetisation architecture only: future products, BBBT Shop, partner infrastructure and a potential commercial Care Pit model. Detailed financial modelling is reserved for diligence.'],
  ['What will ₹1.5 crore fund?', 'The proposed allocation is R&D, tooling, Care Pit technology exploration, gear prototyping, testing/certification and legal/entity work. It is not audited actual expenditure.'],
  ['What are the biggest risks?', 'Operational safety, partner verification, adoption, liability, regulatory requirements, entity structure, external integrations and the difference between community intent and repeat behaviour.'],
  ['What is the investor relationship?', 'A controlled diligence conversation. This public room is not an offer, solicitation, financial advice, funding acceptance or investment commitment.'],
]

function Visual({ type }: { type: string }) {
  if (type === 'opening' || type === 'problem') return <div className="deck-visual deck-visual--photo"><Image src={type === 'opening' ? '/images/investor-brief.png' : '/images/about-solo-rider.png'} alt="Conceptual BBBT investor visual; not a live BBBT operating site." fill sizes="(max-width: 760px) 100vw, 48vw" /></div>
  if (type === 'product') return <div className="deck-visual deck-visual--product"><div className="deck-browser"><div className="deck-browser-bar"><i /><i /><i /></div><div className="deck-ui"><span>BBBT / CURRENT PROTOTYPE</span><strong>Choose your role</strong><b>Rider</b><b>Group Admin</b><b>Founding Rider Council</b><small>Prototype pathway · no payment</small></div></div></div>
  if (type === 'sales-chart') return <div className="deck-visual deck-visual--chart"><div className="chart-kicker">DOMESTIC TWO-WHEELER SALES</div><strong>≈ 1.96 crore</strong><small>FY2024–25 · vehicles sold</small><div className="chart-bars">{[['20–21',.55],['21–22',.72],['22–23',.78],['23–24',.9],['24–25',1]].map(([year,height]) => <div key={String(year)}><i style={{height:`${Number(height)*100}%`}} /><small>FY{year}</small></div>)}</div></div>
  if (type === 'safety-data') return <div className="deck-visual deck-visual--numbers"><span>PROBLEM SCALE</span><strong>MoRTH road-safety burden</strong><div><b>ACCIDENTS</b><b>FATALITIES</b><b>TWO-WHEELER BURDEN</b></div><small>Official source required for final published values · no invented statistic shown</small></div>
  if (type === 'gear-chart') return <div className="deck-visual deck-visual--chart"><div className="chart-kicker">THIRD-PARTY FORECAST</div><div className="forecast"><strong>US$817.7M</strong><span>2024</span><b>→</b><strong>US$1.2051B</strong><span>2030</span></div><div className="cagr">6.8% CAGR</div><small>Grand View Research, 2025 · India motorbike riding gear market</small></div>
  if (type === 'allocation') return <div className="deck-visual deck-visual--allocation"><strong>₹1.50 Cr</strong>{[['35%','Emergency Kit R&D'],['25%','Care Pit R&D'],['20%','Riding Gear'],['12%','Testing'],['8%','Legal / IP']].map(([pct,label]) => <div key={label}><span style={{width:pct}} /><b>{pct}</b><small>{label}</small></div>)}</div>
  if (type === 'matrix') return <div className="deck-visual deck-visual--matrix"><div className="deck-matrix">{matrix.slice(0,6).map(([a,b,c]) => <div key={a}><b>{a}</b><span>{b}</span><small>{c}</small></div>)}</div></div>
  const nodes: Record<string, string[]> = { recovery: ['DISRUPTION','RECOVERY','REBOUND','OPPORTUNITY'], highway: ['NATIONAL','HIGHWAY','MOVEMENT','SUPPORT'], tourism: ['SAFETY','SKILLS','RESCUE','COMMS'], fragmentation: ['RIDER','SAFETY','COMMUNITY','CARE','PARTNERS'], flow: ['RIDER','IDENTITY','COMMUNITY','RIDE','SUPPORT'], ecosystem: ['RIDER','GROUPS','RIDES','FRC','CARE PIT','PARTNERS'], network: ['CREATE','SHARE LINK','JOIN','MEMBERSHIP'], journey: ['START RIDE','CONTEXT','SOS','ESCALATE','CARE PIT'], differentiation: ['RIDER-FIRST','COMMUNITY','PHYSICAL + DIGITAL','ROLE-BASED'], split: ['BBBT TRUST','ACCOUNTABILITY','FUTURE COMMERCIAL','PRODUCTS'], roadmap: ['YEAR 1','YEAR 2','GATES'], commercial: ['SHOP','PRODUCTS','PARTNERS','CARE PIT'], unlock: ['CAPITAL','ENGINEERING','TESTING','FIELD','READINESS'], closing: ['UNDERSTAND','TEST','CHALLENGE','CONVERSE'] }
  return <div className={`deck-visual deck-visual--nodes deck-visual--${type}`}><div className="deck-node-stack">{(nodes[type] || []).map((node, i) => <div key={node} className={i === Math.floor((nodes[type] || []).length / 2) ? 'is-core' : ''}><span>{String(i + 1).padStart(2, '0')}</span>{node}</div>)}</div></div>
}

export default function InvestorDeck() {
  const [active, setActive] = useState(0)
  const [paused, setPaused] = useState(false)
  const [overview, setOverview] = useState(false)
  const [submitted, setSubmitted] = useState(false)
  const [form, setForm] = useState({ name: '', email: '', reason: '' })
  const touchStart = useRef<number | null>(null)
  const go = useCallback((next: number) => setActive((next + slides.length) % slides.length), [])
  useEffect(() => { if (paused) return; const id = window.setInterval(() => setActive((current) => current + 1 >= slides.length ? 0 : current + 1), 10000); return () => window.clearInterval(id) }, [paused])
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === 'ArrowRight') { setPaused(true); go(active + 1) } if (event.key === 'ArrowLeft') { setPaused(true); go(active - 1) } if (event.key === ' ') { event.preventDefault(); setPaused((value) => !value) } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler) }, [active, go])
  const submit = (event: FormEvent) => { event.preventDefault(); setSubmitted(true) }
  const slide = slides[active]
  return <Shell><main className="investor-deck" onTouchStart={(event) => { touchStart.current = event.touches[0]?.clientX || null }} onTouchEnd={(event) => { if (touchStart.current === null) return; const delta = (event.changedTouches[0]?.clientX || 0) - touchStart.current; if (Math.abs(delta) > 45) { setPaused(true); go(active + (delta < 0 ? 1 : -1)) } touchStart.current = null }}>
    <section className="deck-stage" aria-roledescription="slide" aria-label={`Slide ${active + 1} of ${slides.length}: ${slide.title}`}><div className="deck-meta"><span>{slide.section}</span><span>{paused ? 'PAUSED' : 'AUTO · 10 SEC'}</span><button className="deck-overview-toggle" onClick={() => { setPaused(true); setOverview((value) => !value) }}>OVERVIEW</button></div>{overview ? <div className="deck-overview">{slides.map((item, index) => <button key={item.title} className={index === active ? 'is-active' : ''} onClick={() => { setActive(index); setOverview(false) }}><span>{String(index + 1).padStart(2, '0')}</span>{item.title}</button>)}</div> : <><div className="deck-content"><div className="deck-copy"><SectionLabel>{slide.section}</SectionLabel><h1>{slide.title}</h1><p>{slide.message}</p>{slide.tag && <StatusBadge>{slide.tag}</StatusBadge>}{slide.source && <small className="deck-source">{slide.source}</small>}{active === slides.length - 1 && <a className="button button-red" href="#request-access">Request controlled access <ArrowRight aria-hidden="true" /></a>}</div><Visual type={slide.visual} /></div><div className="deck-progress"><span style={{ width: `${((active + 1) / slides.length) * 100}%` }} /></div><div className="deck-controls"><button onClick={() => { setPaused(true); go(active - 1) }} aria-label="Previous slide"><ArrowLeft /></button><button className="deck-play" onClick={() => setPaused((value) => !value)} aria-label={paused ? 'Resume slideshow' : 'Pause slideshow'}>{paused ? <Play /> : <Pause />}</button><button onClick={() => { setPaused(true); go(active + 1) }} aria-label="Next slide"><ArrowRight /></button><span className="deck-control-label">{active + 1} / {slides.length} · {paused ? 'Resume when ready' : 'Auto-advancing'}</span></div></>}</section>
    <section id="request-access" className="deck-access"><SectionLabel>REQUEST CONTROLLED ACCESS</SectionLabel><h2>Start with context.</h2><p>This is a diligence conversation, not an investment checkout. No account, payment, approval or commitment is created here.</p>{submitted ? <div className="investor-confirmation" role="status"><h3>Request received.</h3><p>Thank you. BBBT has recorded your request for manual review. This does not mean investment approval, funding acceptance or commitment.</p></div> : <form className="investor-request-form" onSubmit={submit}><label>Full name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Work email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Reason for exploring BBBT<textarea required minLength={10} rows={4} value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} /></label><label className="investor-check"><input required type="checkbox" />I understand this is a public prototype and not an investment offer.</label><button className="button button-red">Request controlled access <ArrowRight aria-hidden="true" /></button></form>}</section>
    <section className="deck-sources"><SectionLabel>DATA & RESEARCH SOURCES</SectionLabel><h2>Every claim has a verification path.</h2><p>External datasets frame the category. BBBT-specific statements are limited to the current public prototype. Latest source editions and primary operating evidence belong in diligence.</p><div className="deck-source-grid"><article><strong>SIAM</strong><p>Domestic two-wheeler sales, FY2024–25.</p><small>External data · vehicles sold, not active riders.</small></article><article><strong>MoRTH</strong><p>Road-safety and highway infrastructure reports.</p><small>External context · final values require source-year selection.</small></article><article><strong>Ministry of Tourism / PIB</strong><p>Adventure-tourism safety and capacity-building strategy.</p><small>External context · no authoritative rider count claimed.</small></article><article><strong>Grand View Research</strong><p>India motorbike riding-gear market forecast.</p><small>Third-party forecast · not BBBT revenue or market ownership.</small></article></div></section>
    <section className="deck-faq"><SectionLabel>INVESTOR FAQ</SectionLabel><h2>Questions belong in the room.</h2><FAQList items={faqs} /></section>
  </main></Shell>
}
