'use client'

import Image from 'next/image'
import { useCallback, useEffect, useRef, useState } from 'react'
import { ArrowLeft, ArrowRight, Pause, Play } from 'lucide-react'
import { FAQList, SectionLabel, Shell, StatusBadge } from '@/components/public-site'

type Slide = { eyebrow: string; title: string; sub?: string; visual: string; source?: string; tag?: string }

const slides: Slide[] = [
  { eyebrow: '01 / OPEN', title: 'One Nation. One BBBT. Every Rider.', sub: 'Rider safety & community infrastructure.', visual: 'hero', tag: 'CURRENT PROTOTYPE' },
  { eyebrow: '02 / PROBLEM', title: 'When a rider needs help, the system is fragmented.', sub: 'Distance → uncertainty → incident → disconnected support.', visual: 'problem' },
  { eyebrow: '03 / ROAD SAFETY', title: 'The operating context is measurable.', sub: 'India reported 4,80,583 road accidents and 1,72,890 fatalities in 2023.', visual: 'safety', source: 'Source: MoRTH, Road Accidents in India 2023 · official national context.' },
  { eyebrow: '04 / MARKET', title: 'A 19.6M-unit mobility base creates a coordination surface.', sub: 'Domestic two-wheeler sales, FY2024–25.', visual: 'sales', source: 'Source: SIAM · calculated from official annual sales figures. Vehicles sold are not active riders.' },
  { eyebrow: '05 / SIGNAL', title: 'Disruption → recovery → rebound → new safety expectations.', sub: 'A measured post-COVID recovery signal, not a fabricated “rider culture” statistic.', visual: 'recovery' },
  { eyebrow: '06 / GEOGRAPHY', title: 'Longer networks require distributed readiness.', sub: 'India’s National Highway network: 1,46,145 km; approximately 60% above 2014.', visual: 'map', source: 'Source: MoRTH / PIB infrastructure releases · no BBBT locations or coverage claimed.' },
  { eyebrow: '07 / TOURING', title: 'Adventure needs safety, skills, rescue and communication.', visual: 'touring', source: 'Source: Ministry of Tourism / PIB strategy materials.' },
  { eyebrow: '08 / ADJACENCY', title: 'The riding-gear category is a measurable spend signal.', sub: 'US$817.7M in 2024 → US$1.2051B by 2030.', visual: 'gear', source: 'Source: Grand View Research, 2025 · third-party forecast; not BBBT revenue.' },
  { eyebrow: '09 / FRAGMENTATION', title: 'One rider. Eleven disconnected surfaces.', visual: 'matrix' },
  { eyebrow: '10 / SYSTEM', title: 'BBBT connects participation before it promises scale.', visual: 'ecosystem' },
  { eyebrow: '11 / ECOSYSTEM', title: 'A visible status for every capability.', visual: 'network' },
  { eyebrow: '12 / PRODUCT', title: 'The product is walkable today.', sub: 'Current prototype: role selection, signup, identity, groups, rides and referrals.', visual: 'product', tag: 'CURRENT PROTOTYPE' },
  { eyebrow: '13 / NETWORK FLOW', title: 'Participation compounds through simple handoffs.', visual: 'flow' },
  { eyebrow: '14 / SAFETY JOURNEY', title: 'Safety is a chain of dependencies—not a single button.', visual: 'journey' },
  { eyebrow: '15 / DIFFERENTIATION', title: 'Designed differentiation to prove.', visual: 'compare' },
  { eyebrow: '16 / STRUCTURE', title: 'Trust first. Commercial separation by design.', visual: 'trust', tag: 'COMMERCIAL ENTITY NOT YET INCORPORATED' },
  { eyebrow: '17 / BUILD MATRIX', title: 'What exists, what is partial, what comes next.', visual: 'build' },
  { eyebrow: '18 / 24 MONTHS', title: 'Foundation → hardening → validation → readiness.', visual: 'roadmap', tag: 'PLANNED / FUTURE' },
  { eyebrow: '19 / PROPOSED USE', title: '₹1.50 Cr proposed 24-month allocation.', visual: 'allocation', tag: 'PROPOSED · NOT RAISED' },
  { eyebrow: '20 / OUTPUT', title: 'Capital should buy evidence, not theatre.', visual: 'unlock' },
  { eyebrow: '21 / FUTURE', title: 'Now → next → future.', visual: 'future' },
  { eyebrow: '22 / CLOSE', title: 'We have not finished the journey. We have built the foundation.', sub: 'Request controlled investor access.', visual: 'close' },
]

const faq: [string, string][] = [
  ['What exists today?', 'A public prototype with role pathways, signup, identity concepts, dashboards, groups, rides, referrals and public discovery. No user, revenue or coverage metrics are claimed.'],
  ['What is future?', 'Nationwide coverage, dispatch, blood/hospital networks, navigation and weather integrations, verified Care Pits, products and commercial infrastructure.'],
  ['How does BBBT make money?', 'Future products, BBBT Shop, partner infrastructure and a potential commercial Care Pit model. Financial modelling remains a diligence decision.'],
  ['What will ₹1.5 crore fund?', 'Proposed R&D, tooling, gear prototyping, testing/certification and legal/entity work. It is not audited actual expenditure.'],
  ['What are the risks?', 'Safety operations, partner verification, adoption, liability, regulation, entity structure, integrations and repeat behaviour.'],
  ['Is this an investment offer?', 'No. This is a controlled diligence conversation, not an offer, solicitation, advice, approval or commitment.'],
]

const productShots = ['/images/role-brief-rider.png', '/images/safety-check.png', '/images/home-group-ride.png', '/images/community-riders.png', '/images/partner-network.png']

function Visual({ type }: { type: string }) {
  if (type === 'hero') return <div className="pitch-visual pitch-photo"><Image src="/images/investor-brief.png" alt="Conceptual rider safety infrastructure visual" fill sizes="60vw" priority /><b>CONCEPTUAL VISUAL</b></div>
  if (type === 'problem') return <div className="pitch-visual pitch-problem"><div className="problem-flow">{['RIDER','DISTANCE','UNCERTAINTY','INCIDENT','FRAGMENTED SUPPORT'].map((x, i) => <div key={x}><strong>{x}</strong>{i < 4 && <span>→</span>}</div>)}</div><Image src="/images/about-solo-rider.png" alt="Rider on an open road" fill sizes="40vw" /></div>
  if (type === 'safety') return <div className="pitch-visual pitch-stat"><div><span>4,80,583</span><small>ROAD ACCIDENTS</small></div><div><span>1,72,890</span><small>FATALITIES</small></div><i>2023 · MO​​RTH</i></div>
  if (type === 'sales') return <div className="pitch-visual pitch-chart"><span className="visual-label">DOMESTIC TWO-WHEELER SALES · CRORE UNITS</span><div className="bars">{[['20–21',1.51],['21–22',1.34],['22–23',1.59],['23–24',1.78],['24–25',1.96]].map(([year,value]) => <div key={String(year)}><b>{value}</b><i style={{height:`${Number(value)/1.96*100}%`}} /><small>FY {year}</small></div>)}</div><small>CALCULATED FROM SIAM DATA</small></div>
  if (type === 'recovery') return <div className="pitch-visual pitch-timeline"><div className="timeline-line" />{[['2020','COVID DISRUPTION'],['2021–22','RECOVERY'],['2023–24','REBOUND'],['2024–25','MOBILITY SIGNAL']].map(([year,label]) => <div key={year}><b>{year}</b><span>{label}</span></div>)}</div>
  if (type === 'map') return <div className="pitch-visual pitch-map"><Image src="/images/bbbt-highway-hero.png" alt="Conceptual Indian highway network visual" fill sizes="55vw" /><div><strong>1,46,145 km</strong><small>NATIONAL HIGHWAY NETWORK</small><em>CONCEPTUAL NETWORK MODEL · NO BBBT PINS</em></div></div>
  if (type === 'touring') return <div className="pitch-visual pitch-photo"><Image src="/images/how-it-works-road.png" alt="Adventure touring road visual" fill sizes="60vw" /><div className="tour-pillars">{['SAFETY','SKILLS','RESCUE','COMMUNICATION'].map(x => <b key={x}>{x}</b>)}</div></div>
  if (type === 'gear') return <div className="pitch-visual pitch-chart pitch-gear"><span className="visual-label">INDIA MOTORBIKE RIDING GEAR</span><div className="gear-growth"><strong>US$817.7M</strong><i>→</i><strong>US$1.205B</strong></div><b>6.8% CAGR</b><small>2024 → 2030 · THIRD-PARTY FORECAST</small></div>
  if (type === 'matrix') return <div className="pitch-visual pitch-table"><div className="table-head"><b>SURFACE</b><b>TODAY</b><b>BBBT MODEL</b></div>{['Safety','Emergency','Navigation','Weather','Community','Groups','Rides','Highway support','Gear','Knowledge','Partners'].map((x, i) => <div key={x}><span>{x}</span><i>{i % 3 === 0 ? 'separate' : 'fragmented'}</i><b>{i < 6 ? 'connected' : 'designed'}</b></div>)}</div>
  if (type === 'ecosystem') return <div className="pitch-visual pitch-orbit"><div className="orbit-center">BBBT</div>{['RIDER','SAFETY','COMMUNITY','NETWORK','SUPPORT'].map((x, i) => <b key={x} className={`orbit-node n${i}`}>{x}</b>)}</div>
  if (type === 'network') return <div className="pitch-visual pitch-network"><div className="network-core">RIDER</div>{['Identity · WORKING','Groups · PROTOTYPE','Rides · PROTOTYPE','Referrals · PARTIAL','SOS · FUTURE','Care Pits · PROPOSED','Partners · FUTURE'].map((x, i) => <b key={x} className={`net-node net${i}`}>{x}</b>)}</div>
  if (type === 'product') return <div className="pitch-visual pitch-products">{productShots.map((src, i) => <div key={src}><Image src={src} alt={`Current BBBT prototype evidence ${i + 1}`} fill sizes="20vw" /><small>{['ROLE','SAFETY','GROUP','COMMUNITY','PARTNER'][i]}</small></div>)}</div>
  if (type === 'flow') return <div className="pitch-visual pitch-flow">{[['CREATE GROUP','SHARE','JOIN','MEMBERSHIP'],['CREATE RIDE','SHARE','JOIN','RIDE'],['REFERRAL','REGISTRATION','ATTRIBUTION']].map((flow, i) => <div key={i}>{flow.map((x, j) => <b key={x}>{x}{j < flow.length - 1 && <span>↓</span>}</b>)}</div>)}</div>
  if (type === 'journey') return <div className="pitch-visual pitch-journey">{['START RIDE','NAVIGATION','WEATHER','SAFETY','SOS','CONTACTS','BLOOD MESH','CARE PIT','RIDE END'].map((x, i) => <b key={x}><span>{String(i + 1).padStart(2,'0')}</span>{x}<small>{i < 2 ? 'PROTOTYPE' : i < 5 ? 'DEPENDENCY' : 'FUTURE'}</small></b>)}</div>
  if (type === 'compare') return <div className="pitch-visual pitch-compare"><div></div>{['Rider-first','Safety layer','Community','Physical layer','Digital layer','Referral'].map((x, i) => <div key={x}><span>{x}</span><i>{i % 2 ? 'emerging' : 'designed'}</i><b>BBBT</b></div>)}</div>
  if (type === 'trust') return <div className="pitch-visual pitch-architecture"><b>BBBT TRUST<span>safety · governance · welfare</span></b><i>separate responsibility</i><b>FUTURE COMMERCIAL ENTITY<span>products · technology · partnerships · shop</span></b><small>NOT YET INCORPORATED</small></div>
  if (type === 'build') return <div className="pitch-visual pitch-table"><div className="table-head"><b>SYSTEM</b><b>STATUS</b><b>NEXT</b></div>{['Signup','Shared Identity','Groups','Rides','Referrals','Dashboards','SOS','Blood Mesh','Navigation','Weather','Voice Assistant','Care Pits'].map((x, i) => <div key={x}><span>{x}</span><i>{i < 6 ? 'prototype' : i < 9 ? 'dependency' : 'future'}</i><b>{i < 4 ? 'harden' : 'validate'}</b></div>)}</div>
  if (type === 'roadmap') return <div className="pitch-visual pitch-roadmap">{[['0','FOUNDATION'],['1–6','CORE ENGINEERING'],['7–12','HARDENING'],['13–18','VALIDATION'],['19–24','READINESS']].map(([n,x]) => <div key={n}><b>{n}</b><span>{x}</span><i /></div>)}</div>
  if (type === 'allocation') return <div className="pitch-visual pitch-allocation"><strong>₹1.50 Cr</strong>{[['35%','Emergency Kit R&D'],['25%','Care Pit Technology'],['20%','Riding Gear'],['12%','Testing / Certification'],['8%','Legal / IP']].map(([p,x]) => <div key={x}><i style={{width:p}} /><b>{p}</b><span>{x}</span></div>)}</div>
  if (type === 'unlock') return <div className="pitch-visual pitch-funnel">{['CAPITAL','ENGINEERING','HARDENING','TESTING','VALIDATION','READINESS'].map((x, i) => <b key={x} style={{width:`${100 - i * 11}%`}}>{x}<span>→</span></b>)}</div>
  if (type === 'future') return <div className="pitch-visual pitch-future">{[['NOW','prototype'],['NEXT','shared network'],['FUTURE','physical infrastructure']].map(([x,y]) => <div key={x}><b>{x}</b><span>{y}</span></div>)}</div>
  return <div className="pitch-visual pitch-close"><Image src="/images/india-rider-safety.png" alt="Rider safety visual" fill sizes="55vw" /><b>₹1.50 Cr<br /><small>PROPOSED PRE-SEED</small></b></div>
}

export default function InvestorDeck() {
  const [active, setActive] = useState(0); const [paused, setPaused] = useState(false); const [overview, setOverview] = useState(false); const [submitted, setSubmitted] = useState(false); const touch = useRef<number | null>(null)
  const go = useCallback((n:number) => setActive((n + slides.length) % slides.length), [])
  useEffect(() => { if (paused) return; const id = window.setInterval(() => setActive(n => (n + 1) % slides.length), 10000); return () => window.clearInterval(id) }, [paused])
  useEffect(() => { const key = (e:KeyboardEvent) => { if (e.key === 'ArrowRight') { setPaused(true); go(active+1) }; if (e.key === 'ArrowLeft') { setPaused(true); go(active-1) }; if (e.key === ' ') { e.preventDefault(); setPaused(x=>!x) } }; addEventListener('keydown',key); return()=>removeEventListener('keydown',key) }, [active,go])
  const slide = slides[active]
  return <Shell><main className="investor-deck pitch-room" onTouchStart={e=>touch.current=e.touches[0]?.clientX??null} onTouchEnd={e=>{if(touch.current===null)return;const d=(e.changedTouches[0]?.clientX??0)-touch.current;if(Math.abs(d)>45){setPaused(true);go(active+(d<0?1:-1))}touch.current=null}}><section className="pitch-canvas" aria-label={`Slide ${active+1} of ${slides.length}: ${slide.title}`}><header className="pitch-top"><b>BBBT / INVESTOR ROOM</b><span>{slide.eyebrow}</span><button onClick={()=>{setPaused(true);setOverview(v=>!v)}}>{overview?'CLOSE':'OVERVIEW'}</button></header>{overview?<div className="pitch-overview">{slides.map((s,i)=><button key={s.title} className={i===active?'is-active':''} onClick={()=>{setActive(i);setOverview(false)}}><b>{String(i+1).padStart(2,'0')}</b><span>{s.title}</span></button>)}</div>:<><div className="pitch-grid"><div className="pitch-copy"><SectionLabel>{slide.eyebrow}</SectionLabel><h1>{slide.title}</h1>{slide.sub&&<p>{slide.sub}</p>}{slide.tag&&<StatusBadge>{slide.tag}</StatusBadge>}{slide.source&&<small className="pitch-source">{slide.source}</small>}{active===slides.length-1&&<a href="#request-access" className="button button-red">Request investor access <ArrowRight aria-hidden="true" /></a>}</div><Visual type={slide.visual} /></div><div className="pitch-progress"><i style={{width:`${(active+1)/slides.length*100}%`}} /></div><nav className="pitch-controls"><button aria-label="Previous slide" onClick={()=>{setPaused(true);go(active-1)}}><ArrowLeft /></button><button aria-label={paused?'Resume slideshow':'Pause slideshow'} onClick={()=>setPaused(x=>!x)}>{paused?<Play/>:<Pause/>}</button><button aria-label="Next slide" onClick={()=>{setPaused(true);go(active+1)}}><ArrowRight /></button><span>{active+1} / {slides.length} · {paused?'PAUSED':'AUTO 10 SEC'}</span></nav></>}</section><section id="request-access" className="deck-access"><SectionLabel>REQUEST CONTROLLED ACCESS</SectionLabel><h2>Start with context.</h2><p>This is a diligence conversation, not an investment checkout.</p>{submitted?<div className="investor-confirmation" role="status"><h3>Request received.</h3><p>This does not mean investment approval, funding acceptance or commitment.</p></div>:<form className="investor-request-form" onSubmit={e=>{e.preventDefault();setSubmitted(true)}}><label>Full name<input required /></label><label>Work email<input required type="email" /></label><label>Reason for exploring BBBT<textarea required minLength={10} rows={3}/></label><label className="investor-check"><input required type="checkbox" />I understand this is a public prototype and not an investment offer.</label><button className="button button-red">Request investor access <ArrowRight aria-hidden="true" /></button></form>}</section><section className="deck-faq"><SectionLabel>INVESTOR FAQ</SectionLabel><h2>Questions belong in the room.</h2><FAQList items={faq}/></section></main></Shell>
}
