'use client'

import { Cta, FeatureCard, Hero, SectionLabel, Shell, StatusBadge, FAQList, faqItems } from '@/components/public-site'
import { HeartPulse, MapPinned, ShieldCheck, Siren, Users } from 'lucide-react'
const data:{[key:string]:{label:string,title:string,lede:string,heading:string,body:string,features:[string,string,typeof ShieldCheck,string][]}}={
about:{label:'About BBBT Trust',title:'A rider-welfare layer built around trust.',lede:'BBBT Trust is being designed as the non-profit safety, community and governance layer of a larger rider ecosystem.',heading:'Why this exists',body:'Riders already carry deep local knowledge, practical experience and a strong instinct to help. BBBT is a proposed structure for turning that goodwill into clearer safety education, responsible participation and accountable support.',features:[['Safety first','Build safety readiness into everyday riding.',ShieldCheck,'Planned'],['Community voice','Make rider experience part of decision-making.',Users,'Planned'],['Accountability','Keep future administration transparent.',HeartPulse,'Proposed']]},
safety:{label:'Rider Safety Infrastructure',title:'Safety should be part of the ride—not an afterthought.',lede:'A proposed foundation for preparation, education and practical support across critical miles.',heading:'Safety modules',body:'The public prototype describes the intended direction. Capabilities are not presented as live coverage or guaranteed response.',features:[['Safety education','Guides and learning for responsible riding.',ShieldCheck,'Prototype'],['Route readiness','Better preparation for long-distance corridors.',MapPinned,'Planned'],['Rider support','A clearer path to trusted community help.',Users,'Future']]},
emergency:{label:'SOS & Emergency Support',title:'A clearer response path when a ride turns critical.',lede:'BBBT is exploring an emergency-support framework that connects rider contacts, trusted people and future support nodes.',heading:'Intended response layer',body:'This is not a live emergency service. In a future phase, a rider could prepare emergency contacts, share relevant details and access a structured escalation flow.',features:[['1-Tap SOS','A proposed fast-entry emergency flow.',Siren,'Future'],['Emergency contacts','Important people prepared before the ride.',Users,'Planned'],['Blood Mesh concept','A future consent-led blood support network.',HeartPulse,'Future']]},
'care-pits':{label:'Care Pit Network',title:'A human support layer along the highway.',lede:'Care Pits are proposed verified rider-support locations built around real places people already use.',heading:'A network of useful stops',body:'Possible categories include dhabas, hotels, resorts, service pits, cafes, petrol pumps and medical stores. No location is claimed as verified or operational in this prototype.',features:[['Dhaba & cafe','Rest, orient and reconnect with the road.',MapPinned,'Planned'],['Service & pit','Practical support for rider and machine.',ShieldCheck,'Planned'],['Medical support','A future directory of nearby help.',HeartPulse,'Future']]},
community:{label:'Rider Community',title:'The road is shared. The knowledge should be too.',lede:'BBBT is intended to connect riders and local groups around safety, training, responsible riding and mutual support.',heading:'A community with purpose',body:'This is not a social-feed promise. It is a proposed participation layer for people who want better riding culture and practical support around their routes.',features:[['Local rider networks','Connect community knowledge by place.',Users,'Planned'],['Training & knowledge','Share useful, responsible riding practice.',ShieldCheck,'Future'],['Community intelligence','Turn feedback into better decisions.',HeartPulse,'Prototype']]},
'founding-rider-council':{label:'Founding Rider Council',title:'Experience from the road, shaping what comes next.',lede:'A proposed contribution layer for experienced riders and community leaders with deep real-world knowledge.',heading:'Not a social-media badge',body:'Council members are intended to contribute rider expertise, safety education, training input, product testing, research, community needs and honest feedback. Specific financial returns, equity or commissions are not promised at this stage.',features:[['Rider expertise','Bring lived experience into product thinking.',Users,'Proposed'],['Product testing','Help test future rider tools responsibly.',ShieldCheck,'Future'],['Community feedback','Represent real riding pain points.',HeartPulse,'Planned']]}}
export function InfoPage({kind}:{kind:keyof typeof data}){const x=data[kind];return <Shell><main className="role-page"><Hero label={x.label} title={x.title} lede={x.lede}><Cta href="/contact">Start a conversation</Cta></Hero><section className="page-content"><SectionLabel>{x.heading}</SectionLabel><p className="page-lede">{x.body}</p><div className="feature-grid">{x.features.map(([title,body,Icon,status])=><FeatureCard key={title} title={title} icon={Icon} status={status}>{body}</FeatureCard>)}</div></section></main></Shell>}
export function HowItWorks(){return <Shell><main><Hero label="How BBBT works" title="A connected ecosystem, built in clear stages." lede="The proposed BBBT flow starts with rider experience and grows through community responsibility, safety infrastructure and careful research."><Cta href="/#join">Choose your path</Cta></Hero><section className="section"><div className="section-heading"><SectionLabel>The flow</SectionLabel><h2>From the road to better tools.</h2></div><div className="ecosystem-flow">{['Rider identifies a problem','Community shares context','Training builds readiness','Safety network supports action','Care Pits add practical help','Emergency support responds','Intelligence informs research','Future products improve the ride'].map((x,i)=><div className="flow-node" key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></section></main></Shell>}
export function FAQPage(){return <Shell><main><Hero label="Frequently asked questions" title="Clear answers. No inflated claims." lede="A prototype should be honest about what exists, what is planned and what still needs to be built."/><section className="page-content"><FAQList items={faqItems}/></section></main></Shell>}
