'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowRight, ChevronDown, Menu, ShieldCheck, Siren, MapPinned, Users, X } from 'lucide-react'

export function BrandMark() { return <Link href="/" className="brand-mark" aria-label="BBBT home"><span>BBBT</span></Link> }
const nav = [['About','/about'],['Safety','/safety'],['Emergency','/emergency'],['Care Pits','/care-pits'],['Community','/community'],['Council','/founding-rider-council']]
export function Header(){const [open,setOpen]=useState(false);return <header className="site-header"><div className="site-header-inner"><BrandMark/><nav className="desktop-nav" aria-label="Primary navigation">{nav.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</nav><div className="header-actions"><Link className="button button-red header-cta" href="/#join">Join the community <ArrowRight aria-hidden="true"/></Link><button className="menu-button" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label={open?'Close menu':'Open menu'}>{open?<X/>:<Menu/>}</button></div></div>{open&&<nav className="mobile-nav" aria-label="Mobile navigation">{nav.map(([label,href])=><Link key={href} href={href} onClick={()=>setOpen(false)}>{label}</Link>)}<Link href="/how-it-works" onClick={()=>setOpen(false)}>How it works</Link><Link href="/faq" onClick={()=>setOpen(false)}>FAQ</Link><Link className="button button-red" href="/#join">Join the community</Link></nav>}</header>}
export function Footer(){return <footer className="site-footer"><div className="footer-grid"><div><BrandMark/><p>Brand Biker Brotherhood Trust is being designed as a safety, community and rider-welfare layer for India&apos;s riding communities.</p></div><div><h2>Explore</h2><Link href="/safety">Safety infrastructure</Link><Link href="/emergency">Emergency support</Link><Link href="/care-pits">Care Pit network</Link><Link href="/how-it-works">How BBBT works</Link></div><div><h2>Participate</h2><Link href="/community">Rider community</Link><Link href="/founding-rider-council">Founding Rider Council</Link><Link href="/contact">Contact BBBT</Link><Link href="/faq">FAQ</Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} BBBT Trust. Public prototype.</span><span><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/community-guidelines">Community guidelines</Link></span></div></footer>}
export function Shell({children}:{children:React.ReactNode}){return <div className="public-shell"><Header/>{children}<Footer/></div>}
export function SectionLabel({children}:{children:React.ReactNode}){return <p className="section-label">{children}</p>}
export function StatusBadge({children}:{children:React.ReactNode}){return <span className="status-badge">{children}</span>}
export function Hero({label,title,lede,children}:{label:string,title:string,lede:string,children?:React.ReactNode}){return <section className="inner-hero"><div><SectionLabel>{label}</SectionLabel><h1>{title}</h1><p>{lede}</p>{children}</div></section>}
export function FeatureCard({icon:Icon,title,children,status='Planned'}:{icon:typeof ShieldCheck,title:string,children:React.ReactNode,status?:string}){return <article className="feature-card"><div className="feature-icon"><Icon aria-hidden="true"/></div><div className="feature-card-top"><h3>{title}</h3><StatusBadge>{status}</StatusBadge></div><p>{children}</p></article>}
export function JoinSection(){return <section id="join" className="join-section"><SectionLabel>Choose your entry point</SectionLabel><h2>Built with riders, for riders.</h2><p>Choose how you want to contribute to the BBBT ecosystem. This prototype does not create an account or collect payment.</p><div className="join-grid"><Link href="/community" className="join-card"><Users/><strong>Rider or community</strong><span>Explore safety and rider participation <ArrowRight/></span></Link><Link href="/founding-rider-council" className="join-card"><ShieldCheck/><strong>Founding Rider Council</strong><span>Bring real-world rider intelligence <ArrowRight/></span></Link><Link href="/contact" className="join-card"><MapPinned/><strong>Partner or group admin</strong><span>Connect your community or organisation <ArrowRight/></span></Link></div></section>}
export function FAQList({items}:{items:[string,string][]}){const [active,setActive]=useState<number|null>(null);return <div className="faq-list">{items.map(([q,a],i)=><div className="faq-item" key={q}><button onClick={()=>setActive(active===i?null:i)} aria-expanded={active===i}><span>{q}</span><ChevronDown className={active===i?'rotate':''}/></button>{active===i&&<p>{a}</p>}</div>)}</div>}
export const faqItems:[string,string][]=[['What is BBBT?','BBBT, or Brand Biker Brotherhood Trust, is being designed as a safety, community, governance and rider-welfare layer for riding communities in India.'],['Is BBBT currently operational everywhere in India?','No. This public website is a prototype foundation. Coverage, partners and live services will be introduced in controlled future phases.'],['What is a Care Pit?','A Care Pit is a proposed verified rider-support location, such as a dhaba, service point, cafe, petrol pump or medical store.'],['What does BBBT Trust do?','The Trust layer is intended to support safety education, emergency readiness, transparent governance and rider participation.'],['What is the Founding Rider Council?','It is a proposed contribution layer for experienced riders and community leaders who can share expertise, feedback, training input and real-world riding intelligence.'],['Can a group administrator participate?','Yes. Riding-group administrators can contribute community knowledge and connect their local riding communities.'],['Are all features live?','No. Features are labelled Prototype, Planned, Future or Coming Soon so the current state remains clear.'],['Is membership pricing available yet?','No. Membership pricing and commercial token economics are intentionally not shown in this prototype.'],['How can organisations work with BBBT?','Partners can use the contact pathways to start a conversation about safety, community support or future Care Pit participation.'],['How can investors learn about the future ecosystem?','Investors can contact BBBT for a controlled conversation. Public pricing, returns and token mechanics are not part of this phase.']]
export function Cta({href='/contact',children='Talk to BBBT'}:{href?:string,children?:React.ReactNode}){return <Link className="button button-red" href={href}>{children}<ArrowRight aria-hidden="true"/></Link>}
export function EcosystemFlow(){return <div className="ecosystem-flow">{['Rider','Community','Training','Safety network','Care Pits','Emergency support','Community intelligence','Future rider products'].map((x,i)=><div key={x} className="flow-node"><span>{String(i+1).padStart(2,'0')}</span><strong>{x}</strong>{i<7&&<ArrowRight aria-hidden="true"/>}</div>)}</div>}
export { Siren, ShieldCheck, MapPinned, Users }
