'use client'

import Link from 'next/link'
import { ArrowRight, ChevronDown, Menu, X } from 'lucide-react'
import { useState } from 'react'

const nav = [['What is BBBT','/about'],['For Riders','/riders'],['Safety','/safety'],['Community','/community'],['Care Pit','/care-pits'],['Partners','/partners'],['Investor Brief','/investor']]

export function BrandMark(){return <Link href="/" className="brand-mark" aria-label="BBBT home"><span>BBBT</span></Link>}
export function StatusBadge({children, tone='prototype'}:{children:React.ReactNode,tone?:string}){return <span className={`status-badge status-${tone}`}>{children}</span>}
export function Header(){const [open,setOpen]=useState(false);return <header className="site-header"><div className="site-header-inner"><BrandMark/><nav className="desktop-nav" aria-label="Primary navigation">{nav.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</nav><div className="header-actions"><Link className="button button-red" href="#join">Join BBBT <ArrowRight aria-hidden="true"/></Link><Link className="login-link" href="/login">Login</Link><button className="menu-button" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label={open?'Close menu':'Open menu'}>{open?<X/>:<Menu/>}</button></div></div>{open&&<nav className="mobile-nav" aria-label="Mobile navigation">{nav.map(([label,href])=><Link key={href} href={href} onClick={()=>setOpen(false)}>{label}</Link>)}<Link href="#join" onClick={()=>setOpen(false)}>Join BBBT</Link><Link href="/login" onClick={()=>setOpen(false)}>Login</Link></nav>}</header>}
export function Footer(){return <footer className="site-footer"><div className="footer-grid"><div><BrandMark/><p>Brand Biker Brotherhood Trust is being designed as a safety, emergency-support, community and rider-welfare layer for India&apos;s riding communities.</p><StatusBadge>Public prototype</StatusBadge></div><div><h2>Explore</h2><Link href="/about">What is BBBT</Link><Link href="/how-it-works">How it works</Link><Link href="/safety">Rider safety</Link><Link href="/care-pits">Care Pit network</Link></div><div><h2>Participate</h2><Link href="/community">Rider community</Link><Link href="/founding-rider-council">Founding Council</Link><Link href="/contact">Contact BBBT</Link><Link href="/faq">FAQ</Link></div><div><h2>Access</h2><Link href="/signup">Rider signup</Link><Link href="/login">Universal login</Link><Link href="/investor">Investor access</Link><Link href="/admin">BBBT administration</Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} BBBT Trust. Prototype foundation.</span><span><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/community-guidelines">Guidelines</Link></span></div></footer>}
export function Shell({children}:{children:React.ReactNode}){return <div className="public-shell"><Header/>{children}<Footer/></div>}
export function SectionLabel({children}:{children:React.ReactNode}){return <p className="section-label">{children}</p>}
export function Cta({href='/contact',children='Talk to BBBT'}:{href?:string,children?:React.ReactNode}){return <Link className="button button-red" href={href}>{children}<ArrowRight aria-hidden="true"/></Link>}
export function Hero({label,title,lede,children}:{label:string,title:string,lede:string,children?:React.ReactNode}){return <section className="hero"><div className="hero-copy"><SectionLabel>{label}</SectionLabel><h1>{title}</h1><p>{lede}</p>{children&&<div className="hero-actions">{children}</div>}</div></section>}
export function JoinSection(){return <section id="join" className="join-section"><SectionLabel>Choose your entry point</SectionLabel><h2>Built with riders, for riders.</h2><p>Choose how you want to participate in the BBBT ecosystem. This prototype does not create an account or collect payment.</p><div className="join-grid"><Link href="/signup" className="join-card"><strong>Rider</strong><span>Explore safety and community participation <ArrowRight/></span></Link><Link href="/founding-rider-council" className="join-card"><strong>Founding Rider Council</strong><span>Bring real-world rider intelligence <ArrowRight/></span></Link><Link href="/contact" className="join-card"><strong>Group admin or partner</strong><span>Connect your community or organisation <ArrowRight/></span></Link></div></section>}
export function FeatureCard({title,children,icon:Icon,status='Planned',accent='teal'}:{title:string,children:React.ReactNode,icon?:React.ComponentType<{ 'aria-hidden'?: boolean }>,status?:string,accent?:string}){return <article className={`feature-card accent-${accent}`}><div className="feature-card-top">{Icon?<Icon aria-hidden={true}/>:<span className="feature-signal" aria-hidden="true"/>}<h3>{title}</h3></div><p>{children}</p><StatusBadge tone={status.toLowerCase()}>{status}</StatusBadge></article>}
export function FAQList({items}:{items:[string,string][]}){const [active,setActive]=useState<number|null>(null);return <div className="faq-list">{items.map(([q,a],i)=><div className="faq-item" key={q}><button onClick={()=>setActive(active===i?null:i)} aria-expanded={active===i}><span>{q}</span><ChevronDown className={active===i?'rotate':''}/></button>{active===i&&<p>{a}</p>}</div>)}</div>}
export const faqItems:[string,string][]=[['What is BBBT?','BBBT, or Brand Biker Brotherhood Trust, is being designed as a safety, emergency-support, community and rider-welfare layer for India’s riding communities.'],['Is BBBT operational everywhere?','No. This public website is a prototype foundation. Coverage, partners and live services will be introduced in controlled future phases.'],['What is a Care Pit?','A proposed verified rider-support location such as a dhaba, service point, cafe, petrol pump or medical store.'],['Are features live?','No. Features are labelled Prototype, Planned, Future or Coming Soon so simulated systems are not confused with live emergency services.'],['Is membership pricing available?','No. Final membership pricing and token economics are intentionally not shown in this prototype.'],['How can a group or investor participate?','Use the relevant access or contact pathway to start a controlled conversation with BBBT.']]
export { ArrowRight }
