'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { ArrowRight } from 'lucide-react'
import { dashboardFor, demoUsers, sessionKey, type Role, type Status } from '@/lib/prototype-session'

function StatePage({status,role,onBack}:{status:Status;role:Role;onBack:()=>void}){const copy={Pending:['Application Under Review','You will receive an update after BBBT review.'],Rejected:['Application Not Approved','Please contact BBBT support if you believe this needs review.'],Suspended:['Account Suspended','Please contact BBBT support for next steps.']}[status]||['',''];return <main className="auth-shell"><div className="auth-card"><span className="eyebrow orange-text">APPLICATION STATUS / {status.toUpperCase()}</span><h1>{copy[0]}</h1><p><strong>Role applied for:</strong> {role}</p><p><strong>Application status:</strong> {status}</p><p>{copy[1]}</p><Link className="btn btn-cyan" href="/login">RETURN TO LOGIN <ArrowRight size={16}/></Link></div></main>}
export function UniversalLogin(){const [demoId,setDemoId]=useState('rider-approved');const [busy,setBusy]=useState(false);const [state,setState]=useState<{status:Status;role:Role}|null>(null);useEffect(()=>{const params=new URLSearchParams(window.location.search);const status=params.get('status') as Status|null;const role=params.get('role') as Role|null;if(status&&role)setState({status,role})},[]);if(state)return <StatePage status={state.status} role={state.role} onBack={()=>setState(null)}/>;const submit=(id=demoId)=>{const user=demoUsers.find(x=>x.id===id)!;setBusy(true);if(typeof window!=='undefined')sessionStorage.setItem(sessionKey,JSON.stringify({user,activeRole:user.approvedRoles[0]||user.primaryRole}));setTimeout(()=>window.location.assign(user.status==='Approved'?dashboardFor(user.approvedRoles[0]||user.primaryRole):`/login?status=${user.status}&role=${encodeURIComponent(user.primaryRole)}`),250)};return <main className="auth-shell"><div className="auth-card"><Link className="auth-brand" href="/">BBBT</Link><span className="eyebrow cyan-text">UNIVERSAL LOGIN / ONE ACCOUNT</span><h1>Welcome<br/><em>back.</em></h1><p>Use the same BBBT account for your rider, community and approved role access.</p><form className="auth-form" onSubmit={e=>{e.preventDefault();submit()}}><label>EMAIL OR MOBILE<input required placeholder="Email or +91 mobile number"/></label><label>PASSWORD<input required type="password"/></label><button className="btn btn-cyan" disabled={busy}>{busy?'AUTHENTICATING...':'LOGIN'} <ArrowRight size={16}/></button></form><section className="demo-access"><span className="eyebrow orange-text">PROTOTYPE DEMO ACCESS</span><p>Prototype demonstration only — real authentication will be connected before launch.</p><select value={demoId} onChange={e=>setDemoId(e.target.value)}>{demoUsers.map(u=><option key={u.id} value={u.id}>{u.primaryRole} — {u.status}</option>)}</select><button className="btn btn-outline" type="button" onClick={()=>submit()}>USE DEMO IDENTITY</button></section><div className="auth-foot"><Link href="/signup">Create account</Link><span>·</span><button className="text-link" type="button">Forgot password?</button></div></div></main>}
export function UnifiedSignup(){const [done,setDone]=useState(false);const [role,setRole]=useState<Role>('Rider');const [checked,setChecked]=useState(false);if(done)return <main className="auth-shell"><div className="auth-card"><span className="eyebrow green-text">APPLICATION SUBMITTED</span><h1>Access review<br/><em>is pending.</em></h1><p><strong>Role Applied For:</strong> {role}</p><p><strong>Application Status:</strong> Pending</p><p>Your BBBT application has been submitted for review.</p><Link className="btn btn-cyan" href="/login">GO TO LOGIN <ArrowRight size={16}/></Link></div></main>;return <main className="auth-shell"><div className="auth-card auth-wide"><Link className="auth-brand" href="/">BBBT</Link><span className="eyebrow cyan-text">ONE ACCOUNT / ROLE-AWARE ACCESS</span><h1>Create your<br/><em>BBBT account.</em></h1><form className="auth-form" onSubmit={e=>{e.preventDefault();if(checked)setDone(true)}}><label>FULL NAME<input required placeholder="Your full name"/></label><label>MOBILE NUMBER *<input required inputMode="tel" placeholder="+91"/></label><label>EMAIL <input type="email" placeholder="you@example.com"/></label><label>ROLE<select value={role} onChange={e=>setRole(e.target.value as Role)}>{['Rider','Group Admin','Marshal','Founding Rider Council Member'].map(x=><option key={x}>{x}</option>)}</select></label><label className="consent-row"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/><span>I have read and understood my BBBT role responsibilities.</span></label><button className="btn btn-cyan" disabled={!checked}>SUBMIT APPLICATION <ArrowRight size={16}/></button></form></div></main>}
