'use client'

import { useState } from 'react'
import { CloudRain, MapPin, Search, Sun, Wind } from 'lucide-react'

type Forecast = { date: string; max: number; min: number; rain: number; wind: number; code: number }
const places = [{ name: 'Bengaluru', lat: 12.9716, lon: 77.5946 }, { name: 'Mysuru', lat: 12.2958, lon: 76.6394 }, { name: 'Pune', lat: 18.5204, lon: 73.8567 }, { name: 'Delhi', lat: 28.6139, lon: 77.209 }]

function label(code: number) { if (code >= 51) return 'Rain watch'; if (code >= 1) return 'Partly cloudy'; return 'Clear ride' }
export default function WeatherForecast() {
  const [place, setPlace] = useState(places[0]); const [forecast, setForecast] = useState<Forecast[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  async function loadWeather(next = place) { setPlace(next); setLoading(true); setError(''); try { const response = await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${next.lat}&longitude=${next.lon}&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,windspeed_10m_max&forecast_days=5&timezone=auto`); if (!response.ok) throw new Error('Weather unavailable'); const data = await response.json(); setForecast(data.daily.time.map((date: string, i: number) => ({ date, max: Math.round(data.daily.temperature_2m_max[i]), min: Math.round(data.daily.temperature_2m_min[i]), rain: data.daily.precipitation_probability_max[i], wind: Math.round(data.daily.windspeed_10m_max[i]), code: data.daily.weather_code[i] }))) } catch { setError('Live forecast unavailable. Try again shortly.') } finally { setLoading(false) } }
  return <section className="weather-panel" aria-labelledby="weather-heading"><div className="weather-head"><div><span className="eyebrow cyan-text">LIVE RIDER WEATHER / OPEN-METEO</span><h2 id="weather-heading">Plan the next <span>five days.</span></h2><p>Choose a corridor city to see a real forecast before you ride.</p></div><div className="weather-location"><MapPin size={16} /><select value={place.name} onChange={(e) => loadWeather(places.find((item) => item.name === e.target.value) ?? places[0])} aria-label="Choose forecast location">{places.map((item) => <option key={item.name}>{item.name}</option>)}</select><button className="btn btn-cyan" onClick={() => loadWeather()} disabled={loading}><Search size={15} /> {loading ? 'LOADING' : 'UPDATE'}</button></div></div>{error && <p className="weather-error">{error}</p>}{forecast.length > 0 && <div className="forecast-grid">{forecast.map((day) => <article className="forecast-card" key={day.date}><strong>{new Date(day.date).toLocaleDateString('en-IN', { weekday: 'short' })}</strong><span className="forecast-icon">{day.code >= 51 ? <CloudRain size={21} /> : <Sun size={21} />}</span><b>{day.max}° <small>{day.min}°</small></b><span>{label(day.code)}</span><small>{day.rain}% rain · <Wind size={12} /> {day.wind} km/h</small></article>)}</div>}{forecast.length === 0 && !loading && <button className="weather-empty" onClick={() => loadWeather()}>Load live forecast for {place.name}</button>}</section>
}
