'use client'
import type { Question, TrainingTrack } from '@/lib/training-models'
export type ExamStatus='READY'|'IN_PROGRESS'|'SUBMITTED'|'PASSED'|'FAILED'|'EXPIRED'|'VOIDED'
export type ExamType=TrainingTrack
export type ExamBlueprint={blueprintId:string;title:string;examType:ExamType;applicableRoles:string[];trainingProgramIds:string[];questionBankVersion:string;numberOfQuestions:number;passPercentage:number;timeLimitMinutes:number;version:string;status:'DRAFT'|'REVIEW'|'APPROVED'|'PUBLISHED'|'RETIRED';createdBy:string;createdAt:string}
export type ExamAnswer=string[]
export type ExamSession={examSessionId:string;candidateUserId:string;examType:ExamType;blueprintId:string;blueprintVersion:string;selectedQuestionIds:string[];selectedQuestionVersions:string[];startedAt:string;expiresAt:string;submittedAt?:string;status:ExamStatus;answers:Record<string,ExamAnswer>;score?:number;percentage?:number;result?:'PASS'|'FAIL';attemptNumber:number;stars?:number;auditIds:string[]}
export type CertificationRecord={certificationId:string;userId:string;certificationType:ExamType;sourceExamSessionId:string;sourceExamVersion:string;role:string;issuedAt?:string;validFrom?:string;status:'PENDING'|'ELIGIBLE'|'ISSUED'|'SUSPENDED'|'REVOKED'|'EXPIRED';issuingAuthority:'FRC_APPROVAL_REQUIRED';stars:number}
export type ExamAudit={id:string;action:string;actorId:string;targetId:string;createdAt:string;immutable:true}
export const examStoreKey='bbbt-prototype-examination'
export const defaultBlueprints:ExamBlueprint[]=[{blueprintId:'BP-COMMON-SAFETY-V1',title:'Common Rider Safety Examination',examType:'COMMON_RIDER_SAFETY',applicableRoles:['Rider','Group Admin','Marshal','Founding Rider Council Member'],trainingProgramIds:['TRN-COMMON-RIDER-V1'],questionBankVersion:'1.0.0',numberOfQuestions:4,passPercentage:75,timeLimitMinutes:20,version:'1.0.0',status:'PUBLISHED',createdBy:'council-approved',createdAt:'2026-01-01T00:00:00.000Z'}]
export type ExamStore={blueprints:ExamBlueprint[];sessions:ExamSession[];certifications:CertificationRecord[];audit:ExamAudit[]}
export function readExamStore():ExamStore{if(typeof window==='undefined')return {blueprints:defaultBlueprints,sessions:[],certifications:[],audit:[]};try{const raw=sessionStorage.getItem(examStoreKey);return raw?JSON.parse(raw):{blueprints:defaultBlueprints,sessions:[],certifications:[],audit:[]}}catch{return {blueprints:defaultBlueprints,sessions:[],certifications:[],audit:[]}}}
export function writeExamStore(s:ExamStore){sessionStorage.setItem(examStoreKey,JSON.stringify(s))}
export function calculateStars(p:number){return p>=90?5:p>=80?4:p>=75?3:p>=60?2:p>=40?1:0}
export function answersEqual(a:string[],b:string[]){return a.length===b.length&&a.every(x=>b.includes(x))}
export function scoreExam(questions:Question[],answers:Record<string,ExamAnswer>,passPercentage=75){const correct=questions.filter(q=>answersEqual(answers[q.id]||[],q.correctAnswer));const total=questions.reduce((n,q)=>n+1,0);const percentage=total?Math.round(correct.length/total*100):0;return {correct:correct.length,total,percentage,pass:percentage>=passPercentage,stars:calculateStars(percentage)}}
export function eligibility(store:ExamStore,userId:string,blueprint:ExamBlueprint){const now=Date.now();const active=store.sessions.find(s=>s.candidateUserId===userId&&s.examType===blueprint.examType&&s.status==='IN_PROGRESS');if(active)return {ok:false,reason:'ACTIVE_SESSION_EXISTS'};const attempts=store.sessions.filter(s=>s.candidateUserId===userId&&s.examType===blueprint.examType&&s.status!=='VOIDED');const year=new Date().getFullYear();if(attempts.filter(s=>new Date(s.startedAt).getFullYear()===year).length>=2)return {ok:false,reason:'ATTEMPT_LIMIT_REACHED'};const last=attempts.sort((a,b)=>b.startedAt.localeCompare(a.startedAt))[0];if(last&&now-Date.parse(last.startedAt)<15552000000)return {ok:false,reason:'COOLDOWN_ACTIVE'};if(blueprint.status!=='PUBLISHED')return {ok:false,reason:'EXAM_NOT_PUBLISHED'};return {ok:true,reason:'ELIGIBLE'}}
export function questionsForExam(questions:Question[],blueprint:ExamBlueprint){return questions.filter(q=>q.status==='PUBLISHED'&&q.applicableRoles.some(r=>blueprint.applicableRoles.includes(r))).slice(0,blueprint.numberOfQuestions)}
