export type LanguageCode='en'|'hi'|'bn'|'ta'|'te'|'mr'|'gu'|'kn'|'ml'|'pa'|'ar'
export type CurrencyCode='INR'|'USD'|'EUR'|'GBP'|'AED'|'SGD'
export type LanguageOption={code:LanguageCode;label:string;nativeLabel:string;dir:'ltr'|'rtl';fallback:'en'|'hi'}
export const preferenceKey='bbbt-global-preferences'
export const languages:LanguageOption[]=[{code:'en',label:'English',nativeLabel:'English',dir:'ltr',fallback:'en'},{code:'hi',label:'Hindi',nativeLabel:'हिन्दी',dir:'ltr',fallback:'hi'},{code:'bn',label:'Bengali',nativeLabel:'বাংলা',dir:'ltr',fallback:'en'},{code:'ta',label:'Tamil',nativeLabel:'தமிழ்',dir:'ltr',fallback:'en'},{code:'te',label:'Telugu',nativeLabel:'తెలుగు',dir:'ltr',fallback:'en'},{code:'mr',label:'Marathi',nativeLabel:'मराठी',dir:'ltr',fallback:'hi'},{code:'gu',label:'Gujarati',nativeLabel:'ગુજરાતી',dir:'ltr',fallback:'hi'},{code:'kn',label:'Kannada',nativeLabel:'ಕನ್ನಡ',dir:'ltr',fallback:'en'},{code:'ml',label:'Malayalam',nativeLabel:'മലയാളം',dir:'ltr',fallback:'en'},{code:'pa',label:'Punjabi',nativeLabel:'ਪੰਜਾਬੀ',dir:'ltr',fallback:'hi'},{code:'ar',label:'Arabic',nativeLabel:'العربية',dir:'rtl',fallback:'en'}]
export const currencies:Record<CurrencyCode,{label:string;symbol:string;locale:string;rateNote:string}>= {'INR':{label:'Indian Rupee',symbol:'₹',locale:'en-IN',rateNote:'Source values remain in INR'},'USD':{label:'US Dollar',symbol:'$',locale:'en-US',rateNote:'Prototype display conversion'},'EUR':{label:'Euro',symbol:'€',locale:'de-DE',rateNote:'Prototype display conversion'},'GBP':{label:'British Pound',symbol:'£',locale:'en-GB',rateNote:'Prototype display conversion'},'AED':{label:'UAE Dirham',symbol:'د.إ',locale:'en-AE',rateNote:'Prototype display conversion'},'SGD':{label:'Singapore Dollar',symbol:'S$',locale:'en-SG',rateNote:'Prototype display conversion'}}
export type Preferences={language:LanguageCode;currency:CurrencyCode}
export const defaultPreferences:Preferences={language:'en',currency:'INR'}
export function languageFor(code:LanguageCode){return languages.find(x=>x.code===code)||languages[0]}
export function formatMoney(value:number,currency:CurrencyCode='INR'){return new Intl.NumberFormat(currencies[currency].locale,{style:'currency',currency,maximumFractionDigits:0}).format(value)}
export function readPreferences():Preferences{if(typeof window==='undefined')return defaultPreferences;try{return {...defaultPreferences,...JSON.parse(sessionStorage.getItem(preferenceKey)||'{}')}}catch{return defaultPreferences}}
export function savePreferences(p:Preferences){try{sessionStorage.setItem(preferenceKey,JSON.stringify(p))}catch{}}
