export type LanguageCode='en'|'hi'|'ur'|'bn'|'as'|'or'|'pa'|'gu'|'mr'|'gom'|'kn'|'ml'|'ta'|'te'|'ks'|'sd'|'ne'|'mai'|'sa'|'brx'|'doi'|'mni'|'sat'|'ar'
export type CurrencyCode='INR'|'USD'|'EUR'|'GBP'|'AED'|'SGD'
export type LanguageOption={code:LanguageCode;label:string;nativeLabel:string;dir:'ltr'|'rtl';fallback:'en'|'hi'}
export const preferenceKey='bbbt-global-preferences'
export const languages:LanguageOption[]=[{code:'en',label:'English',nativeLabel:'English',dir:'ltr',fallback:'en'},{code:'hi',label:'Hindi',nativeLabel:'हिन्दी',dir:'ltr',fallback:'hi'},{code:'ur',label:'Urdu',nativeLabel:'اردو',dir:'rtl',fallback:'en'},{code:'bn',label:'Bengali',nativeLabel:'বাংলা',dir:'ltr',fallback:'en'},{code:'as',label:'Assamese',nativeLabel:'অসমীয়া',dir:'ltr',fallback:'en'},{code:'or',label:'Odia',nativeLabel:'ଓଡ଼ିଆ',dir:'ltr',fallback:'en'},{code:'pa',label:'Punjabi',nativeLabel:'ਪੰਜਾਬੀ',dir:'ltr',fallback:'hi'},{code:'gu',label:'Gujarati',nativeLabel:'ગુજરાતી',dir:'ltr',fallback:'hi'},{code:'mr',label:'Marathi',nativeLabel:'मराठी',dir:'ltr',fallback:'hi'},{code:'gom',label:'Konkani',nativeLabel:'कोंकणी',dir:'ltr',fallback:'mr'},{code:'kn',label:'Kannada',nativeLabel:'ಕನ್ನಡ',dir:'ltr',fallback:'en'},{code:'ml',label:'Malayalam',nativeLabel:'മലയാളം',dir:'ltr',fallback:'en'},{code:'ta',label:'Tamil',nativeLabel:'தமிழ்',dir:'ltr',fallback:'en'},{code:'te',label:'Telugu',nativeLabel:'తెలుగు',dir:'ltr',fallback:'en'},{code:'ks',label:'Kashmiri',nativeLabel:'कॉशुर',dir:'rtl',fallback:'ur'},{code:'sd',label:'Sindhi',nativeLabel:'سنڌي',dir:'rtl',fallback:'ur'},{code:'ne',label:'Nepali',nativeLabel:'नेपाली',dir:'ltr',fallback:'hi'},{code:'mai',label:'Maithili',nativeLabel:'मैथिली',dir:'ltr',fallback:'hi'},{code:'sa',label:'Sanskrit',nativeLabel:'संस्कृतम्',dir:'ltr',fallback:'hi'},{code:'brx',label:'Bodo',nativeLabel:'बड़ो',dir:'ltr',fallback:'hi'},{code:'doi',label:'Dogri',nativeLabel:'डोगरी',dir:'ltr',fallback:'hi'},{code:'mni',label:'Manipuri / Meitei',nativeLabel:'মৈতৈলোন্',dir:'ltr',fallback:'bn'},{code:'sat',label:'Santali',nativeLabel:'ᱥᱟᱱᱛᱟᱲᱤ',dir:'ltr',fallback:'hi'},{code:'ar',label:'Arabic',nativeLabel:'العربية',dir:'rtl',fallback:'en'}]
export const currencies:Record<CurrencyCode,{label:string;symbol:string;locale:string;rateNote:string}>= {'INR':{label:'Indian Rupee',symbol:'₹',locale:'en-IN',rateNote:'Source values remain in INR'},'USD':{label:'US Dollar',symbol:'$',locale:'en-US',rateNote:'Prototype display conversion'},'EUR':{label:'Euro',symbol:'€',locale:'de-DE',rateNote:'Prototype display conversion'},'GBP':{label:'British Pound',symbol:'£',locale:'en-GB',rateNote:'Prototype display conversion'},'AED':{label:'UAE Dirham',symbol:'د.إ',locale:'en-AE',rateNote:'Prototype display conversion'},'SGD':{label:'Singapore Dollar',symbol:'S$',locale:'en-SG',rateNote:'Prototype display conversion'}}
export type Preferences={language:LanguageCode;currency:CurrencyCode}
export const defaultPreferences:Preferences={language:'en',currency:'INR'}
export function languageFor(code:LanguageCode){return languages.find(x=>x.code===code)||languages[0]}
const prototypeRates:Record<CurrencyCode,number>={INR:1,USD:0.012,EUR:0.011,GBP:0.0095,AED:0.044,SGD:0.016}
export function formatMoney(sourceAmount:number,displayCurrency:CurrencyCode='INR',sourceCurrency:CurrencyCode='INR'){const converted=sourceAmount*(prototypeRates[displayCurrency]/prototypeRates[sourceCurrency]);return new Intl.NumberFormat(currencies[displayCurrency].locale,{style:'currency',currency:displayCurrency,maximumFractionDigits:0}).format(converted)}
export function readPreferences():Preferences{if(typeof document==='undefined')return defaultPreferences;try{const stored=document.cookie.split('; ').find(cookie=>cookie.startsWith(`${preferenceKey}=`))?.split('=')[1];return {...defaultPreferences,...JSON.parse(stored?decodeURIComponent(stored):'{}')}}catch{return defaultPreferences}}
export function savePreferences(p:Preferences){try{document.cookie=`${preferenceKey}=${encodeURIComponent(JSON.stringify(p))}; Path=/; Max-Age=31536000; SameSite=Lax`}catch{}}
