export type ProductStatus='CONCEPT'|'PROTOTYPE'|'FIELD_TEST'|'REVISION'|'RETEST'|'FRC_APPROVED'|'RELEASE_CANDIDATE'|'RETIRED'|'SUPERSEDED'
export type TestResult='PASS'|'FAIL'|'CONDITIONAL'|'INCONCLUSIVE'
export type TestFinalStatus='TEST_PENDING'|'TEST_COMPLETED'|'RETEST_REQUIRED'|'PASSED'|'FAILED'|'CLOSED'
export type CommercialStatus='DRAFT'|'REVIEW'|'APPROVED'|'REJECTED'|'SUPERSEDED'
export type ProductConcept={productId:string;productName:string;category:string;description:string;safetyObjective:string;problemStatement:string;targetRiderOrRole:string;conceptOwner:string;currentVersionId:string;status:ProductStatus;createdAt:string;updatedAt:string}
export type ProductVersion={versionId:string;productId:string;versionNumber:string;changeSummary:string;prototypeDetails:string;safetyRequirements:string;manufacturingNotes:string;createdBy:string;createdAt:string;reviewStatus:'PENDING'|'IN_REVIEW'|'APPROVED'|'REJECTED';status:ProductStatus}
export type ProductFieldTest={testId:string;productId:string;versionId:string;testType:string;tester:string;testerRole:string;location:string;district:string;zone:string;testDate:string;testConditions:string;result:TestResult;defects:string;safetyConcerns:string;recommendations:string;retestRequired:boolean;attachments:string[];finalStatus:TestFinalStatus;createdAt:string;updatedAt:string}
export type ProductRetest={retestId:string;originalTestId:string;productId:string;versionId:string;retestDate:string;tester:string;location:string;conditions:string;result:TestResult;defects:string;safetyConcerns:string;recommendations:string;finalStatus:TestFinalStatus;createdAt:string}
export type CommercialReview={reviewId:string;productId:string;versionId:string;manufacturingCost?:number;packagingCost?:number;testingCost?:number;logisticsCost?:number;platformPaymentCost?:number;totalEstimatedCost:number;marginRecommendation?:string;proposedMRP?:number;proposedSellingPrice?:number;approvalStatus:CommercialStatus;effectiveDate?:string;reviewer?:string;approver?:string;createdAt:string;updatedAt:string}
export type ProductAudit={id:string;action:string;actorId:string;role:string;scope:string;target:string;notes?:string;createdAt:string;immutable:true}
export const productLabKey='bbbt-product-lab'
export const productLifecycle:Record<ProductStatus,ProductStatus[]>={CONCEPT:['PROTOTYPE','RETIRED'],PROTOTYPE:['FIELD_TEST','REVISION','RETIRED'],FIELD_TEST:['REVISION','RETEST','FRC_APPROVED'],REVISION:['FIELD_TEST','RETEST','RETIRED'],RETEST:['FIELD_TEST','FRC_APPROVED','REVISION'],FRC_APPROVED:['RELEASE_CANDIDATE','SUPERSEDED'],RELEASE_CANDIDATE:['RETIRED','SUPERSEDED'],RETIRED:[],SUPERSEDED:[]}
export function canTransition(from:ProductStatus,to:ProductStatus){return productLifecycle[from].includes(to)}
export function totalCost(review:CommercialReview){return (review.manufacturingCost||0)+(review.packagingCost||0)+(review.testingCost||0)+(review.logisticsCost||0)+(review.platformPaymentCost||0)}
export function emptyProductState(){return {products:[] as ProductConcept[],versions:[] as ProductVersion[],tests:[] as ProductFieldTest[],retests:[] as ProductRetest[],commercial:[] as CommercialReview[],pricing:[] as {productId:string;versionId:string;mrp:number;sellingPrice:number;status:'PROPOSED'|'APPROVED';approver:string;effectiveDate:string}[],audit:[] as ProductAudit[]}}
export function readProductState(){try{if(typeof window==='undefined')return emptyProductState();const raw=sessionStorage.getItem(productLabKey);const parsed=raw?JSON.parse(raw):emptyProductState();return {...emptyProductState(),...parsed,retests:parsed.retests||[],pricing:parsed.pricing||[]}}catch{return emptyProductState()}}
export function saveProductState(state:ReturnType<typeof emptyProductState>){sessionStorage.setItem(productLabKey,JSON.stringify(state))}
export function stableId(prefix:string){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`}
export function releaseChecklist(state:ReturnType<typeof emptyProductState>,product:ProductConcept){const version=state.versions.find(v=>v.versionId===product.currentVersionId);const tests=state.tests.filter(t=>t.productId===product.productId&&t.versionId===product.currentVersionId);const retestBlocked=tests.some(t=>t.retestRequired&&!state.retests.some(r=>r.originalTestId===t.testId&&['PASSED','CLOSED'].includes(r.finalStatus)));const testing=tests.length>0&&tests.every(t=>['TEST_COMPLETED','PASSED','CLOSED'].includes(t.finalStatus));const approval=product.status==='FRC_APPROVED'||product.status==='RELEASE_CANDIDATE';const commercial=state.commercial.some(c=>c.productId===product.productId&&c.versionId===product.currentVersionId&&c.approvalStatus==='APPROVED');const pricing=state.pricing.some(p=>p.productId===product.productId&&p.versionId===product.currentVersionId&&p.status==='APPROVED');return {version:Boolean(version),testing,retests:!retestBlocked,approval,commercial,pricing,ready:Boolean(version&&testing&&!retestBlocked&&approval&&commercial&&pricing)}}

export const defaultQuestions=[]
