export type ProductStatus='CONCEPT'|'PROTOTYPE'|'FIELD_TEST'|'REVISION'|'RETEST'|'FRC_APPROVED'|'RELEASE_CANDIDATE'|'RETIRED'|'SUPERSEDED'
export type TestResult='PASS'|'FAIL'|'CONDITIONAL'|'INCONCLUSIVE'
export type TestFinalStatus='TEST_PENDING'|'TEST_COMPLETED'|'RETEST_REQUIRED'|'PASSED'|'FAILED'|'CLOSED'
export type CommercialStatus='DRAFT'|'REVIEW'|'APPROVED'|'REJECTED'|'SUPERSEDED'
export type ProductConcept={productId:string;productName:string;category:string;description:string;safetyObjective:string;problemStatement:string;targetRiderOrRole:string;conceptOwner:string;currentVersionId:string;status:ProductStatus;createdAt:string;updatedAt:string}
export type ProductVersion={versionId:string;productId:string;versionNumber:string;changeSummary:string;prototypeDetails:string;safetyRequirements:string;manufacturingNotes:string;createdBy:string;createdAt:string;reviewer?:string;reviewStatus:'PENDING'|'IN_REVIEW'|'APPROVED'|'REJECTED';status:ProductStatus}
export type ProductFieldTest={testId:string;productId:string;versionId:string;testType:string;tester:string;testerRole:string;location:string;district:string;zone:string;testDate:string;testConditions:string;result:TestResult;defects:string;safetyConcerns:string;recommendations:string;retestRequired:boolean;attachments:string[];finalStatus:TestFinalStatus;createdAt:string;updatedAt:string}
export type CommercialReview={reviewId:string;productId:string;versionId:string;manufacturingCost?:number;packagingCost?:number;testingCost?:number;logisticsCost?:number;platformPaymentCost?:number;totalEstimatedCost:number;marginRecommendation?:string;proposedMRP?:number;proposedSellingPrice?:number;approvalStatus:CommercialStatus;effectiveDate?:string;reviewer?:string;approver?:string;createdAt:string;updatedAt:string}
export const productLabKey='bbbt-product-lab'
export const productLifecycle:Record<ProductStatus,ProductStatus[]>={CONCEPT:['PROTOTYPE','RETIRED'],PROTOTYPE:['FIELD_TEST','REVISION','RETIRED'],FIELD_TEST:['REVISION','RETEST','FRC_APPROVED'],REVISION:['FIELD_TEST','RETEST','RETIRED'],RETEST:['FIELD_TEST','FRC_APPROVED','REVISION'],FRC_APPROVED:['RELEASE_CANDIDATE','SUPERSEDED'],RELEASE_CANDIDATE:['RETIRED','SUPERSEDED'],RETIRED:[],SUPERSEDED:[]}
export function canTransition(from:ProductStatus,to:ProductStatus){return productLifecycle[from].includes(to)}
export function totalCost(review:CommercialReview){return (review.manufacturingCost||0)+(review.packagingCost||0)+(review.testingCost||0)+(review.logisticsCost||0)+(review.platformPaymentCost||0)}
export function emptyProductState(){return {products:[] as ProductConcept[],versions:[] as ProductVersion[],tests:[] as ProductFieldTest[],commercial:[] as CommercialReview[],audit:[] as {id:string;action:string;actorId:string;scope:string;target:string;createdAt:string;immutable:true}[]}}
export function readProductState(){try{if(typeof window==='undefined')return emptyProductState();const raw=sessionStorage.getItem(productLabKey);return raw?JSON.parse(raw):emptyProductState()}catch{return emptyProductState()}}
export function saveProductState(state:ReturnType<typeof emptyProductState>){sessionStorage.setItem(productLabKey,JSON.stringify(state))}
