import type { DemoUser, PrototypeGroup, PrototypeIdentity, PrototypeVehicle, GovernanceRide, OpenRide } from '@/lib/prototype-session'
import { readRegistry, identityKey, groupKey, openRidesKey, sessionKey } from '@/lib/prototype-session'
import { readExamStore } from '@/lib/exam-models'
import { readProductState } from '@/lib/product-lab-models'
import { readTrainingStore } from '@/lib/training-models'

export type DataSource='BBBT_ACTUAL'|'USER_SELF_DECLARED'|'SYSTEM_DERIVED'|'EXTERNAL_OFFICIAL'|'EXTERNAL_TRUSTED'|'MODEL_DERIVED'|'BBBT_PROJECTION'|'UNAVAILABLE'
export type Geography={country:string;state:string;district:string;city:string;pinCode:string;bbbtZone:string;source:DataSource}
export type LocationContext={displayName:string;pin:string;city:string;district:string;state:string;bbbtZone:string;latitude:number|null;longitude:number|null;source:DataSource;status:'UNAVAILABLE'|'USER_ENTERED'|'DERIVED'}
export type RouteContext={plannedOrigin:LocationContext|null;plannedDestination:LocationContext|null;summary:string|null;distanceKm:number|null;estimatedDurationMinutes:number|null;plannedDeparture:string|null;plannedArrival:string|null;status:'NOT_STARTED'|'PLANNED'|'ACTIVE'|'COMPLETED';returnRoute:LocationContext|null;revisions:number}
export type WeatherContext={queryLocation:LocationContext|null;weatherDate:string|null;timestamp:string|null;source:DataSource;temperature:number|null;condition:string|null;rainfallProbability:number|null;precipitation:number|null;wind:string|null;visibility:string|null;warnings:string[];forecastPeriod:string|null}
export type RideContext={rideId:string;rideType:'GOVERNED'|'OPEN';creatorRiderId:string;title:string;image:null;status:string;rideMode:'SOLO_RIDE'|'GROUP_RIDE'|null;associatedGroupId:string|null;origin:LocationContext|null;destination:LocationContext|null;rideDate:string|null;participantCount:number;participantIds:string[];createdAt:string;updatedAt:string;route:RouteContext;weather:WeatherContext}
export type SafetyReadiness={safetyKitStatus:'ACTIVE'|'NOT ACTIVATED'|'UNAVAILABLE';linkedVehicleId:string|null;profileCompletion:boolean;verificationState:string;bloodGroupState:'PRESENT'|'MISSING';emergencyContactComplete:boolean;trainingAttemptStatus:string;latestExamState:string;certificationState:string;applicableRoles:string[]}
export type ActivityEventType=string
export type ActivityEvent={eventId:string;eventType:ActivityEventType;actorRiderId:string|null;role:string|null;scope:string|null;targetType:string|null;targetId:string|null;timestamp:string;metadata:Record<string,string|number|boolean|null>;source:string;prototypeVersion:string}
export type HelpMetadata={helpId:string;feature:string;title:string;whatItDoes:string;whyItMatters:string;whoCanUseIt:string[];status:'PREPARED'|'ACTIVE';prototypeNote?:string}
export const activityKey='bbbt-prototype-activity'
export const emptyLocation=():LocationContext=>({displayName:'',pin:'',city:'',district:'',state:'',bbbtZone:'',latitude:null,longitude:null,source:'UNAVAILABLE',status:'UNAVAILABLE'})
export const emptyRoute=():RouteContext=>({plannedOrigin:null,plannedDestination:null,summary:null,distanceKm:null,estimatedDurationMinutes:null,plannedDeparture:null,plannedArrival:null,status:'NOT_STARTED',returnRoute:null,revisions:0})
export const emptyWeather=():WeatherContext=>({queryLocation:null,weatherDate:null,timestamp:null,source:'UNAVAILABLE',temperature:null,condition:null,rainfallProbability:null,precipitation:null,wind:null,visibility:null,warnings:[],forecastPeriod:null})
export function geographyFor(identity:PrototypeIdentity|null):Geography{return {country:'India',state:identity?.state||'',district:identity?.district||'',city:identity?.city||'',pinCode:identity?.pinCode||'',bbbtZone:identity?.bbbtZone||'',source:identity?.bbbtZone?'SYSTEM_DERIVED':'UNAVAILABLE'}}
export function vehicleReference(v:PrototypeVehicle){return {vehicleId:v.id,manufacturer:v.make,model:v.model,modelYear:v.modelYear,currentKm:v.currentKm,registration:v.registration,manufacturerNormalized:v.make.trim().toLowerCase(),modelNormalized:v.model.trim().toLowerCase(),engineCC:null,category:null,source:'USER_SELF_DECLARED' as DataSource}}
export function safetyReadiness(identity:PrototypeIdentity|null,user:DemoUser|null):SafetyReadiness{const kit=identity?.safetyKit;return {safetyKitStatus:kit?.status||'UNAVAILABLE',linkedVehicleId:kit?.linkedVehicleId||null,profileCompletion:Boolean(identity?.fullName&&identity.handle&&identity.mobile&&identity.email&&identity.city&&identity.pinCode),verificationState:identity?.status||user?.status||'UNAVAILABLE',bloodGroupState:identity?.bloodGroup?'PRESENT':'MISSING',emergencyContactComplete:Boolean(identity?.emergencyName&&identity.emergencyNumber),trainingAttemptStatus:'REFER_TO_TRAINING_STORE',latestExamState:'REFER_TO_EXAM_STORE',certificationState:'FRC_APPROVAL_REQUIRED',applicableRoles:user?.approvedRoles||[]}}
export function rideContext(ride:GovernanceRide|OpenRide,kind:'GOVERNED'|'OPEN',identity:PrototypeIdentity|null):RideContext{const isOpen=kind==='OPEN';return {rideId:ride.id,rideType:kind,creatorRiderId:isOpen?(ride as OpenRide).creatorId:(ride as GovernanceRide).createdAt?identity?.id||'unknown':'unknown',title:ride.title,image:null,status:ride.status,rideMode:null,associatedGroupId:null,origin:null,destination:null,rideDate:ride.date||null,participantCount:isOpen?(ride as OpenRide).participants.length:Object.keys((ride as GovernanceRide).participants||{}).length,participantIds:isOpen?(ride as OpenRide).participants.map(p=>p.id):Object.keys((ride as GovernanceRide).participants||{}),createdAt:ride.createdAt,updatedAt:ride.createdAt,route:emptyRoute(),weather:emptyWeather()}}
export function readActivity():ActivityEvent[]{try{const raw=sessionStorage.getItem(activityKey);const parsed=raw?JSON.parse(raw):[];return Array.isArray(parsed)?parsed:[]}catch{return []}}
export function appendActivity(event:Omit<ActivityEvent,'eventId'|'timestamp'|'prototypeVersion'>){const next={...event,eventId:`EVT-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,timestamp:new Date().toISOString(),prototypeVersion:'3K'};const current=readActivity();sessionStorage.setItem(activityKey,JSON.stringify([...current,next]));return next}
export function riderJourneySnapshot(user:DemoUser|null){let identity:PrototypeIdentity|null=null;let group:PrototypeGroup|null=null;let open:OpenRide[]=[];try{identity=JSON.parse(sessionStorage.getItem(identityKey)||'null');group=JSON.parse(sessionStorage.getItem(groupKey)||'null');open=JSON.parse(sessionStorage.getItem(openRidesKey)||'[]')}catch{};const exam=readExamStore();const training=readTrainingStore();const product=readProductState();return {riderId:identity?.id||user?.id||null,geography:geographyFor(identity),vehicles:(identity?.vehicles||[]).map(vehicleReference),safety:safetyReadiness(identity,user),groups:group?[group.id]:[],rides:[...(group?.rides||[]).map(r=>rideContext(r,'GOVERNED',identity)),...open.map(r=>rideContext(r,'OPEN',identity))],trainingActivity:training.audit.length,examActivity:exam.audit.length,productTestingActivity:product.tests.filter(t=>t.tester===user?.name).length,eventCount:readActivity().filter(e=>e.actorRiderId===(identity?.id||user?.id)).length,source:'BBBT_ACTUAL' as DataSource}}
export const helpMetadata:HelpMetadata[]=[{helpId:'rider-context',feature:'Rider Journey',title:'Rider Context',whatItDoes:'Connects your profile, vehicles, geography, readiness, groups, rides, and activity through stable references.',whyItMatters:'Future navigation, weather, SOS, Blood Mesh, and analytics can use one consistent rider context.',whoCanUseIt:['Rider','Group Admin','Marshal','Founding Rider Council Member'],status:'PREPARED',prototypeNote:'Prototype data only; no live location or external services.'}]
export function dataInspection(){return {riderIds:readRegistry().map(x=>x.id),activityCount:readActivity().length,sessionPresent:typeof window!=='undefined'&&Boolean(sessionStorage.getItem(sessionKey))}}
