export type TrainingStatus='DRAFT'|'REVIEW'|'APPROVED'|'PUBLISHED'|'RETIRED'
export type TrainingTrack='COMMON_RIDER_SAFETY'|'GROUP_ADMIN'|'GROUP_MARSHAL'|'INDEPENDENT_MARSHAL'|'FRC_GOVERNANCE'
export type TrainingRole='Rider'|'Group Admin'|'Marshal'|'Founding Rider Council Member'
export type TrainingLesson={id:string;title:string;topic:string;content:string;mediaReference?:string;language:string;version:string;status:TrainingStatus;createdBy:string;reviewedBy?:string;createdAt:string;updatedAt:string}
export type TrainingModule={id:string;title:string;description:string;topic:string;sequence:number;applicableRoles:TrainingRole[];lessons:TrainingLesson[];language:string;version:string;status:TrainingStatus;createdBy:string;reviewedBy?:string;createdAt:string;updatedAt:string}
export type TrainingProgram={id:string;title:string;description:string;track:TrainingTrack;applicableRoles:TrainingRole[];modules:TrainingModule[];version:string;status:TrainingStatus;createdBy:string;reviewedBy?:string;createdAt:string;updatedAt:string;publishedAt?:string;retiredAt?:string;supersedesId?:string}
export type QuestionType='SINGLE_CHOICE'|'MULTIPLE_CHOICE'|'TRUE_FALSE'|'SCENARIO_BASED'
export type Question={id:string;category:string;topic:string;difficulty:'FOUNDATION'|'INTERMEDIATE'|'ADVANCED';type:QuestionType;text:string;options:string[];correctAnswer:string[];explanation:string;mediaReference?:string;language:string;applicableRoles:TrainingRole[];status:TrainingStatus;version:string;createdBy:string;reviewedBy?:string;createdAt:string;updatedAt:string;supersedesId?:string}
export type TrainingAudit={id:string;action:string;actorId:string;targetId:string;createdAt:string;immutable:true}
export const trainingStoreKey='bbbt-prototype-training-studio'
export const defaultTrainingPrograms:TrainingProgram[]=[{id:'TRN-COMMON-RIDER-V1',title:'Common Rider Safety Training',description:'Reusable safety awareness content for every operational role.',track:'COMMON_RIDER_SAFETY',applicableRoles:['Rider','Group Admin','Marshal','Founding Rider Council Member'],modules:['Rider safety fundamentals','Road signs and rules','Hand signals and formation','Hazard and emergency awareness','SOS and Safety Kit awareness'].map((title,i)=>({id:`MOD-COMMON-${i+1}`,title,description:'Prototype governed content structure; not medical, legal, government, or professional certification.',topic:title,sequence:i+1,applicableRoles:['Rider','Group Admin','Marshal','Founding Rider Council Member'],lessons:[],language:'English',version:'1.0.0',status:'DRAFT',createdBy:'council-approved',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})),version:'1.0.0',status:'DRAFT',createdBy:'council-approved',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}]
export const defaultQuestions:Question[]=[{id:'Q-COMMON-1',category:'Safety',topic:'Protective equipment',difficulty:'FOUNDATION',type:'SINGLE_CHOICE',text:'What should a rider verify before every ride?',options:['Protective equipment and vehicle readiness','Only the weather','Only the fuel level'],correctAnswer:['Protective equipment and vehicle readiness'],explanation:'A safe pre-ride check includes the rider, vehicle, and environment.',language:'English',applicableRoles:['Rider','Group Admin','Marshal','Founding Rider Council Member'],status:'PUBLISHED',version:'1.0.0',createdBy:'council-approved',createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z'},{id:'Q-COMMON-2',category:'Safety',topic:'Formation',difficulty:'FOUNDATION',type:'TRUE_FALSE',text:'A rider should maintain a safe following distance.',options:['True','False'],correctAnswer:['True'],explanation:'Following distance provides time to react.',language:'English',applicableRoles:['Rider','Group Admin','Marshal','Founding Rider Council Member'],status:'PUBLISHED',version:'1.0.0',createdBy:'council-approved',createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z'},{id:'Q-COMMON-3',category:'Emergency',topic:'SOS',difficulty:'INTERMEDIATE',type:'MULTIPLE_CHOICE',text:'Which actions support a safe incident response?',options:['Stop in a safe location','Use SOS procedures','Ignore the incident'],correctAnswer:['Stop in a safe location','Use SOS procedures'],explanation:'Move to safety and use the established response flow.',language:'English',applicableRoles:['Rider','Group Admin','Marshal','Founding Rider Council Member'],status:'PUBLISHED',version:'1.0.0',createdBy:'council-approved',createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z'},{id:'Q-COMMON-4',category:'Signals',topic:'Communication',difficulty:'FOUNDATION',type:'SCENARIO_BASED',text:'A hazard appears ahead during a governed ride. What is the best response?',options:['Signal clearly and reduce speed','Accelerate toward it','Leave the formation without signaling'],correctAnswer:['Signal clearly and reduce speed'],explanation:'Clear signals and controlled speed protect the formation.',language:'English',applicableRoles:['Rider','Group Admin','Marshal','Founding Rider Council Member'],status:'PUBLISHED',version:'1.0.0',createdBy:'council-approved',createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z'}]
export function readTrainingStore(){if(typeof window==='undefined')return {programs:defaultTrainingPrograms,questions:defaultQuestions,audit:[] as TrainingAudit[]};try{const raw=sessionStorage.getItem(trainingStoreKey);return raw?JSON.parse(raw):{programs:defaultTrainingPrograms,questions:defaultQuestions,audit:[]}}catch{return {programs:defaultTrainingPrograms,questions:defaultQuestions,audit:[]}}}
export function writeTrainingStore(store:ReturnType<typeof readTrainingStore>){sessionStorage.setItem(trainingStoreKey,JSON.stringify(store))}
export function canTrainingAction(level:'DISTRICT'|'ZONE'|'MASTER',approval:string,action:string){if(approval!=='ACTIVE')return false;if(action==='VIEW'||action==='REVIEW')return true;if(level==='MASTER')return ['CREATE','EDIT','APPROVE','PUBLISH','RETIRE','VERSION'].includes(action);if(level==='ZONE')return ['CREATE','EDIT'].includes(action);return action==='CREATE'}
export function validQuestion(q:Question){return !!q.text.trim()&&q.options.length>=2&&q.correctAnswer.length>0&&q.correctAnswer.every(a=>q.options.includes(a))&&!!q.explanation.trim()}
