export type TrainingStatus='DRAFT'|'REVIEW'|'APPROVED'|'PUBLISHED'|'RETIRED'
export type TrainingTrack='COMMON_RIDER_SAFETY'|'GROUP_ADMIN'|'GROUP_MARSHAL'|'INDEPENDENT_MARSHAL'|'FRC_GOVERNANCE'
export type TrainingRole='Rider'|'Group Admin'|'Marshal'|'Founding Rider Council Member'
export type TrainingLesson={id:string;title:string;topic:string;content:string;mediaReference?:string;language:string;version:string;status:TrainingStatus;createdBy:string;reviewedBy?:string;createdAt:string;updatedAt:string}
export type TrainingModule={id:string;title:string;description:string;topic:string;sequence:number;applicableRoles:TrainingRole[];lessons:TrainingLesson[];language:string;version:string;status:TrainingStatus;createdBy:string;reviewedBy?:string;createdAt:string;updatedAt:string}
export type TrainingProgram={id:string;title:string;description:string;track:TrainingTrack;applicableRoles:TrainingRole[];modules:TrainingModule[];version:string;status:TrainingStatus;createdBy:string;reviewedBy?:string;createdAt:string;updatedAt:string;publishedAt?:string;retiredAt?:string;supersedesId?:string}
export type QuestionType='SINGLE_CHOICE'|'MULTIPLE_CHOICE'|'TRUE_FALSE'|'SCENARIO_BASED'
export type Question={id:string;category:string;topic:string;difficulty:'FOUNDATION'|'INTERMEDIATE'|'ADVANCED';type:QuestionType;text:string;options:string[];correctAnswer:string[];explanation:string;mediaReference?:string;language:string;applicableRoles:TrainingRole[];status:TrainingStatus;version:string;createdBy:string;reviewedBy?:string;createdAt:string;updatedAt:string;supersedesId?:string}
export type TrainingAudit={id:string;action:string;actorId:string;targetId:string;createdAt:string;immutable:true}
export const trainingStoreKey='bbbt-prototype-training-studio'
export const defaultTrainingPrograms:TrainingProgram[]=[{id:'TRN-COMMON-RIDER-V1',title:'Common Rider Safety Training',description:'Reusable safety awareness content for every operational role.',track:'COMMON_RIDER_SAFETY',applicableRoles:['Rider','Group Admin','Marshal','Founding Rider Council Member'],modules:['Rider safety fundamentals','Road signs and rules','Hand signals and formation','Hazard and emergency awareness','SOS and Safety Kit awareness'].map((title,i)=>({id:`MOD-COMMON-${i+1}`,title,description:'Prototype governed content structure; not medical, legal, government, or professional certification.',topic:title,sequence:i+1,applicableRoles:['Rider','Group Admin','Marshal','Founding Rider Council Member'],lessons:[],language:'English',version:'1.0.0',status:'DRAFT',createdBy:'council-approved',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})),version:'1.0.0',status:'DRAFT',createdBy:'council-approved',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}]
export const defaultQuestions:Question[]=[]
export function readTrainingStore(){if(typeof window==='undefined')return {programs:defaultTrainingPrograms,questions:defaultQuestions,audit:[] as TrainingAudit[]};try{const raw=sessionStorage.getItem(trainingStoreKey);return raw?JSON.parse(raw):{programs:defaultTrainingPrograms,questions:defaultQuestions,audit:[]}}catch{return {programs:defaultTrainingPrograms,questions:defaultQuestions,audit:[]}}}
export function writeTrainingStore(store:ReturnType<typeof readTrainingStore>){sessionStorage.setItem(trainingStoreKey,JSON.stringify(store))}
export function canTrainingAction(level:'DISTRICT'|'ZONE'|'MASTER',approval:string,action:string){if(approval!=='ACTIVE')return false;if(action==='VIEW'||action==='REVIEW')return true;if(level==='MASTER')return ['CREATE','EDIT','APPROVE','PUBLISH','RETIRE','VERSION'].includes(action);if(level==='ZONE')return ['CREATE','EDIT'].includes(action);return action==='CREATE'}
export function validQuestion(q:Question){return !!q.text.trim()&&q.options.length>=2&&q.correctAnswer.length>0&&q.correctAnswer.every(a=>q.options.includes(a))&&!!q.explanation.trim()}
